'use client'
import Link from 'next/link'
import { useLang } from '../lang-context'
import { useSaved } from '../saved-context'
import { tr, COMMON } from '../translations'

const ITEM = { href: '/dashboard/apps', title: 'Recommended Apps', titleJP: 'おすすめアプリ', icon: 'apps', color: '#b22620' }
function tl(m: Record<string, string>, l: string) { return m[l] ?? m['EN'] }

const TITLE = { EN: 'Recommended Apps', JP: 'おすすめアプリ', ZH: '推荐应用', 'ZH-T': '推薦應用', KO: '추천 앱', ES: 'Apps Recomendadas', FR: 'Applications Recommandées', IT: 'App Consigliate', TL: 'Mga Inirerekomendang App', ID: 'Aplikasi yang Direkomendasikan', DE: 'Empfohlene Apps', PT: 'Aplicativos Recomendados', RU: 'Рекомендованные приложения' }
const SUB = { EN: 'Free apps to help you navigate healthcare in Japan — symptom checking, translation, disaster alerts, and medication records.', JP: '日本での医療をサポートする無料アプリ。症状チェック・翻訳・防災・お薬手帳など。', ZH: '帮助您在日本就医的免费应用——症状检查、翻译、防灾警报和用药记录。', 'ZH-T': '幫助您在日本就醫的免費應用——症狀檢查、翻譯、防災警報和用藥記錄。', KO: '일본에서 의료를 지원하는 무료 앱 — 증상 확인, 번역, 재난 경보, 약 복용 기록.', ES: 'Apps gratuitas para navegar la atención médica en Japón.', FR: 'Applications gratuites pour naviguer dans les soins de santé au Japon.', IT: "App gratuite per navigare nell'assistenza sanitaria in Giappone.", TL: 'Mga libreng app para tulungan kang mag-navigate ng healthcare sa Japan.', ID: 'Aplikasi gratis untuk membantu navigasi layanan kesehatan di Jepang.', DE: 'Kostenlose Apps für die Gesundheitsversorgung in Japan.', PT: 'Apps gratuitos para navegar os cuidados de saúde no Japão.', RU: 'Бесплатные приложения для здравоохранения в Японии.' }

const APPS = [
  {
    icon: 'symptoms',
    color: '#b22620',
    bg: '#fff5f5',
    name: { EN: 'Ubie (ユビー)', JP: 'ユビー', ZH: 'Ubie (ユビー)', 'ZH-T': 'Ubie (ユビー)', KO: 'Ubie (ユビー)', ES: 'Ubie (ユビー)', FR: 'Ubie (ユビー)', IT: 'Ubie (ユビー)', TL: 'Ubie (ユビー)', ID: 'Ubie (ユビー)', DE: 'Ubie (ユビー)', PT: 'Ubie (ユビー)', RU: 'Ubie (ユビー)' },
    url: 'https://ubie.app/',
    badge: 'iOS · Android · Free',
    category: { EN: 'Symptom Checker', JP: '症状チェッカー', ZH: '症状检查', 'ZH-T': '症狀檢查', KO: '증상 체커', ES: 'Verificador de Síntomas', FR: 'Vérificateur de Symptômes', IT: 'Controllo Sintomi', TL: 'Symptom Checker', ID: 'Pemeriksa Gejala', DE: 'Symptomprüfer', PT: 'Verificador de Sintomas', RU: 'Проверка симптомов' },
    desc: { EN: 'AI-powered symptom checker available in English and Japanese. Answer a few questions and get a list of possible conditions and recommended departments to visit. Widely used across Japan.', JP: 'AIによる症状チェッカー。英語・日本語に対応。いくつかの質問に答えると、考えられる病気と受診すべき診療科がわかります。日本全国で広く利用されています。', ZH: '英日双语AI症状检查工具。回答几个问题，即可获得可能的病情列表和推荐就诊科室。在日本广泛使用。', 'ZH-T': '英日雙語AI症狀檢查工具。回答幾個問題，即可獲得可能的病情列表和推薦就診科室。在日本廣泛使用。', KO: 'AI 기반 증상 체커로 영어와 일본어를 지원합니다. 몇 가지 질문에 답하면 가능한 상태 목록과 추천 진료과를 알 수 있습니다. 일본 전국에서 널리 사용됩니다.', ES: 'Verificador de síntomas con IA disponible en inglés y japonés. Responde algunas preguntas y obtén una lista de posibles enfermedades y departamentos recomendados. Ampliamente usado en Japón.', FR: "Vérificateur de symptômes par IA disponible en anglais et japonais. Répondez à quelques questions et obtenez une liste de conditions possibles et les services recommandés. Largement utilisé au Japon.", IT: "Controllo sintomi basato su IA disponibile in inglese e giapponese. Rispondi ad alcune domande e ottieni un elenco di possibili patologie e reparti consigliati. Ampiamente usato in Giappone.", TL: 'AI-powered na symptom checker na available sa Ingles at Japanese. Sagutin ang ilang tanong at makuha ang listahan ng posibleng kondisyon at rekomendasyon ng departamento. Malawakang ginagamit sa Japan.', ID: 'Pemeriksa gejala berbasis AI tersedia dalam bahasa Inggris dan Jepang. Jawab beberapa pertanyaan dan dapatkan daftar kondisi yang mungkin dan departemen yang direkomendasikan. Banyak digunakan di Jepang.', DE: 'KI-gestützter Symptomprüfer auf Englisch und Japanisch. Beantworte einige Fragen und erhalte eine Liste möglicher Erkrankungen und empfohlener Abteilungen. In Japan weit verbreitet.', PT: 'Verificador de sintomas com IA disponível em inglês e japonês. Responda algumas perguntas e obtenha uma lista de condições possíveis e departamentos recomendados. Amplamente usado no Japão.', RU: 'Проверка симптомов на основе ИИ, доступная на английском и японском языках. Ответьте на несколько вопросов и получите список возможных состояний и рекомендуемых отделений. Широко используется в Японии.' },
    tips: { EN: ['Available in English — no Japanese required', 'Shows which clinic type to visit (内科, 外科, etc.)', 'Can be shown to the doctor as a symptom summary'], JP: ['英語対応で日本語不要', '受診すべき診療科（内科・外科など）が分かる', '医師に症状サマリーとして見せることができる'], ZH: ['提供英语版本，无需日语', '显示应就诊的科室（内科、外科等）', '可作为症状摘要给医生看'], 'ZH-T': ['提供英語版本，無需日語', '顯示應就診的科室（內科、外科等）', '可作為症狀摘要給醫生看'], KO: ['영어로 이용 가능 — 일본어 불필요', '방문해야 할 클리닉 유형 표시(내과, 외과 등)', '의사에게 증상 요약으로 보여줄 수 있음'], ES: ['Disponible en inglés — no se requiere japonés', 'Muestra qué tipo de clínica visitar (内科, 外科, etc.)', 'Se puede mostrar al médico como resumen de síntomas'], FR: ['Disponible en anglais — pas de japonais requis', 'Indique le type de clinique à visiter (内科, 外科, etc.)', 'Peut être montré au médecin comme résumé des symptômes'], IT: ['Disponibile in inglese — nessun giapponese richiesto', 'Mostra quale tipo di clinica visitare (内科, 外科, ecc.)', 'Può essere mostrato al medico come riepilogo dei sintomi'], TL: ['Available sa Ingles — hindi kailangan ng Japanese', 'Nagpapakita kung anong uri ng klinika ang bisitahin (内科, 外科, atbp.)', 'Maaaring ipakita sa doktor bilang symptom summary'], ID: ['Tersedia dalam bahasa Inggris — tidak perlu bahasa Jepang', 'Menunjukkan jenis klinik yang harus dikunjungi (内科, 外科, dll.)', 'Dapat ditunjukkan ke dokter sebagai ringkasan gejala'], DE: ['Auf Englisch verfügbar — kein Japanisch erforderlich', 'Zeigt, welchen Kliniktyp man aufsuchen soll (内科, 外科, etc.)', 'Kann dem Arzt als Symptomzusammenfassung gezeigt werden'], PT: ['Disponível em inglês — sem necessidade de japonês', 'Mostra qual tipo de clínica visitar (内科, 外科, etc.)', 'Pode ser mostrado ao médico como resumo dos sintomas'], RU: ['Доступен на английском языке — японский не нужен', 'Показывает, какой тип клиники посетить (内科, 外科 и т.д.)', 'Можно показать врачу как сводку симптомов'] },
  },
  {
    icon: 'translate',
    color: '#206777',
    bg: '#eef7f9',
    name: { EN: 'VoiceTra (ボイストラ)', JP: 'ボイストラ', ZH: 'VoiceTra (ボイストラ)', 'ZH-T': 'VoiceTra (ボイストラ)', KO: 'VoiceTra (ボイストラ)', ES: 'VoiceTra (ボイストラ)', FR: 'VoiceTra (ボイストラ)', IT: 'VoiceTra (ボイストラ)', TL: 'VoiceTra (ボイストラ)', ID: 'VoiceTra (ボイストラ)', DE: 'VoiceTra (ボイストラ)', PT: 'VoiceTra (ボイストラ)', RU: 'VoiceTra (ボイストラ)' },
    url: 'https://voicetra.nict.go.jp/',
    badge: 'iOS · Android · Free',
    category: { EN: 'Medical Translation', JP: '医療翻訳', ZH: '医疗翻译', 'ZH-T': '醫療翻譯', KO: '의료 번역', ES: 'Traducción Médica', FR: 'Traduction Médicale', IT: 'Traduzione Medica', TL: 'Medical Translation', ID: 'Terjemahan Medis', DE: 'Medizinische Übersetzung', PT: 'Tradução Médica', RU: 'Медицинский перевод' },
    desc: { EN: "Free voice translation app developed by NICT (Japan's national research institute), specifically designed for medical consultations. Supports 31 languages. Speak naturally and it translates in real time.", JP: '情報通信研究機構（NICT）が開発した無料音声翻訳アプリ。医療現場専用に設計されており、31言語に対応。自然に話すとリアルタイムで翻訳されます。', ZH: '由NICT（日本国家研究机构）开发的免费语音翻译应用，专为医疗问诊设计。支持31种语言，自然说话即可实时翻译。', 'ZH-T': '由NICT（日本國家研究機構）開發的免費語音翻譯應用，專為醫療問診設計。支持31種語言，自然說話即可即時翻譯。', KO: 'NICT(일본 국가 연구 기관)에서 개발한 무료 음성 번역 앱으로 의료 상담 전용으로 설계되었습니다. 31개 언어를 지원하며 자연스럽게 말하면 실시간으로 번역됩니다.', ES: 'App gratuita de traducción de voz desarrollada por NICT (instituto nacional de investigación de Japón), diseñada específicamente para consultas médicas. Soporta 31 idiomas.', FR: "Application gratuite de traduction vocale développée par le NICT (Institut national de recherche du Japon), conçue spécifiquement pour les consultations médicales. Supporte 31 langues.", IT: "App di traduzione vocale gratuita sviluppata dal NICT (istituto di ricerca nazionale giapponese), progettata specificamente per consultazioni mediche. Supporta 31 lingue.", TL: 'Libreng voice translation app na ginawa ng NICT (pambansang research institute ng Japan), partikular na dinisenyo para sa medical consultations. Sumusuporta ng 31 na wika.', ID: 'Aplikasi terjemahan suara gratis yang dikembangkan oleh NICT (lembaga penelitian nasional Jepang), dirancang khusus untuk konsultasi medis. Mendukung 31 bahasa.', DE: 'Kostenlose Sprachübersetzungs-App, entwickelt vom NICT (nationales Forschungsinstitut Japans), speziell für medizinische Beratungen konzipiert. Unterstützt 31 Sprachen.', PT: 'App de tradução de voz gratuito desenvolvido pelo NICT (instituto de pesquisa nacional do Japão), especificamente projetado para consultas médicas. Suporta 31 idiomas.', RU: 'Бесплатное голосовое приложение для перевода, разработанное NICT (национальный исследовательский институт Японии), специально для медицинских консультаций. Поддерживает 31 язык.' },
    tips: { EN: ['Designed specifically for medical consultations', 'Works offline for some languages', "Can show translated text to the doctor's screen"], JP: ['医療相談専用に設計されている', '一部の言語はオフラインで動作', '翻訳されたテキストを医師の画面に見せることができる'], ZH: ['专为医疗问诊设计', '部分语言支持离线使用', '可将翻译文本展示给医生看'], 'ZH-T': ['專為醫療問診設計', '部分語言支持離線使用', '可將翻譯文本展示給醫生看'], KO: ['의료 상담을 위해 특별히 설계됨', '일부 언어는 오프라인으로 작동', '번역된 텍스트를 의사 화면에 보여줄 수 있음'], ES: ['Diseñada específicamente para consultas médicas', 'Funciona sin conexión para algunos idiomas', 'Puede mostrar el texto traducido en la pantalla del médico'], FR: ['Conçue spécifiquement pour les consultations médicales', 'Fonctionne hors ligne pour certaines langues', "Peut afficher le texte traduit sur l'écran du médecin"], IT: ['Progettata specificamente per consultazioni mediche', 'Funziona offline per alcune lingue', "Può mostrare il testo tradotto allo schermo del medico"], TL: ['Dinisenyo partikular para sa medical consultations', 'Gumagana offline para sa ilang wika', 'Maaaring ipakita ang translated text sa screen ng doktor'], ID: ['Dirancang khusus untuk konsultasi medis', 'Bekerja offline untuk beberapa bahasa', 'Dapat menampilkan teks terjemahan ke layar dokter'], DE: ['Speziell für medizinische Beratungen konzipiert', 'Funktioniert offline für einige Sprachen', 'Kann übersetzten Text auf dem Bildschirm des Arztes anzeigen'], PT: ['Projetado especificamente para consultas médicas', 'Funciona offline para alguns idiomas', 'Pode mostrar texto traduzido na tela do médico'], RU: ['Разработано специально для медицинских консультаций', 'Работает офлайн для некоторых языков', 'Может показывать переведённый текст на экране врача'] },
  },
  {
    icon: 'emergency_home',
    color: '#b45309',
    bg: '#fffbeb',
    name: { EN: 'Safety Tips', JP: 'Safety Tips', ZH: 'Safety Tips', 'ZH-T': 'Safety Tips', KO: 'Safety Tips', ES: 'Safety Tips', FR: 'Safety Tips', IT: 'Safety Tips', TL: 'Safety Tips', ID: 'Safety Tips', DE: 'Safety Tips', PT: 'Safety Tips', RU: 'Safety Tips' },
    url: 'https://www.jnto.go.jp/safety-tips/eng/app.html',
    badge: 'iOS · Android · Free',
    category: { EN: 'Disaster Alerts', JP: '防災アラート', ZH: '防灾警报', 'ZH-T': '防災警報', KO: '재난 경보', ES: 'Alertas de Desastres', FR: 'Alertes Catastrophes', IT: 'Allerte Catastrofi', TL: 'Disaster Alerts', ID: 'Peringatan Bencana', DE: 'Katastrophenwarnungen', PT: 'Alertas de Desastres', RU: 'Предупреждения о бедствиях' },
    desc: { EN: 'Official Japan Tourism Agency disaster alert app. Receive earthquake, tsunami, and severe weather warnings in your language the moment they are issued. Supports 14 languages including English, Chinese, Korean, and more.', JP: '観光庁公式の防災アラートアプリ。地震・津波・悪天候の警報を発令と同時に多言語で受信。英語・中国語・韓国語など14言語対応。', ZH: '日本观光厅官方防灾警报应用。地震、海啸和恶劣天气警报发出时立即以您的语言接收。支持包括英语、中文、韩语在内的14种语言。', 'ZH-T': '日本觀光廳官方防災警報應用。地震、海嘯和惡劣天氣警報發出時立即以您的語言接收。支持包括英語、中文、韓語在內的14種語言。', KO: '일본 관광청 공식 재난 경보 앱. 지진, 쓰나미, 악천후 경보를 발령 즉시 귀하의 언어로 수신합니다. 영어, 중국어, 한국어 등 14개 언어 지원.', ES: 'App oficial de alertas de desastres de la Agencia de Turismo de Japón. Recibe avisos de terremoto, tsunami y mal tiempo en tu idioma en el momento en que se emiten. 14 idiomas.', FR: "Application officielle d'alerte aux catastrophes de l'Agence japonaise du tourisme. Recevez les avertissements de tremblement de terre, tsunami et météo sévère dans votre langue dès leur émission. 14 langues.", IT: "App ufficiale di allerta catastrofi dell'Agenzia Turismo Giapponese. Ricevi avvisi di terremoto, tsunami e maltempo nella tua lingua nel momento in cui vengono emessi. 14 lingue.", TL: 'Opisyal na disaster alert app ng Japan Tourism Agency. Makatanggap ng earthquake, tsunami, at severe weather warnings sa iyong wika sa sandaling mai-isyu ang mga ito. 14 na wika.', ID: 'Aplikasi peringatan bencana resmi Badan Pariwisata Jepang. Terima peringatan gempa, tsunami, dan cuaca buruk dalam bahasa Anda saat diterbitkan. Mendukung 14 bahasa.', DE: 'Offizielle Katastrophen-Alarm-App der Japanischen Tourismusbehörde. Erhalte Erdbeben-, Tsunami- und Unwetterwarnungen in deiner Sprache, sobald sie ausgegeben werden. 14 Sprachen.', PT: 'App oficial de alertas de desastres da Agência de Turismo do Japão. Receba avisos de terremoto, tsunami e mau tempo no seu idioma assim que forem emitidos. 14 idiomas.', RU: 'Официальное приложение для оповещения о стихийных бедствиях Японского агентства туризма. Получайте предупреждения о землетрясениях, цунами и непогоде на вашем языке в момент их выпуска. 14 языков.' },
    tips: { EN: ['Install before an emergency — not during', 'Enable push notifications for real-time alerts', 'Shows evacuation site maps for your area'], JP: ['緊急時ではなく、事前にインストールすること', 'プッシュ通知を有効にしてリアルタイムで受信', '近隣の避難場所マップが確認できる'], ZH: ['在紧急情况前安装，而不是紧急时', '启用推送通知以获取实时警报', '显示您所在区域的疏散地点地图'], 'ZH-T': ['在緊急情況前安裝，而不是緊急時', '啟用推送通知以獲取即時警報', '顯示您所在區域的疏散地點地圖'], KO: ['긴급 상황 중이 아닌 미리 설치하세요', '실시간 알림을 위한 푸시 알림 활성화', '해당 지역 대피 장소 지도 표시'], ES: ['Instala antes de una emergencia — no durante', 'Activa las notificaciones push para alertas en tiempo real', 'Muestra mapas de sitios de evacuación de tu área'], FR: ["Installez avant une urgence — pas pendant", 'Activez les notifications push pour les alertes en temps réel', "Affiche les cartes des sites d'évacuation de votre zone"], IT: ["Installa prima di un'emergenza — non durante", 'Abilita le notifiche push per avvisi in tempo reale', 'Mostra mappe dei siti di evacuazione della tua area'], TL: ['I-install bago ang emergency — hindi habang may emergency', 'I-enable ang push notifications para sa real-time alerts', 'Nagpapakita ng evacuation site maps para sa iyong lugar'], ID: ['Pasang sebelum keadaan darurat — bukan saat darurat', 'Aktifkan notifikasi push untuk peringatan real-time', 'Menampilkan peta lokasi evakuasi di area Anda'], DE: ['Vor einem Notfall installieren — nicht währenddessen', 'Push-Benachrichtigungen für Echtzeitwarnungen aktivieren', 'Zeigt Evakuierungskartenstandorte für Ihre Region'], PT: ['Instale antes de uma emergência — não durante', 'Ative notificações push para alertas em tempo real', 'Mostra mapas de locais de evacuação da sua área'], RU: ['Установите до чрезвычайной ситуации, не во время', 'Включите push-уведомления для оповещений в реальном времени', 'Показывает карты мест эвакуации в вашем районе'] },
  },
  {
    icon: 'medication',
    color: '#4a7c59',
    bg: '#f0fdf4',
    name: { EN: 'Okusuri Techo Apps', JP: 'お薬手帳アプリ', ZH: 'Okusuri Techo应用', 'ZH-T': 'Okusuri Techo應用', KO: 'Okusuri Techo 앱', ES: 'Apps Okusuri Techo', FR: 'Apps Okusuri Techo', IT: 'App Okusuri Techo', TL: 'Okusuri Techo Apps', ID: 'Aplikasi Okusuri Techo', DE: 'Okusuri Techo Apps', PT: 'Apps Okusuri Techo', RU: 'Приложения Okusuri Techo' },
    url: 'https://www.epark.jp/lp/okusuri/',
    badge: 'iOS · Android · Free',
    category: { EN: 'Medication Record', JP: '服薬管理', ZH: '服药记录', 'ZH-T': '服藥記錄', KO: '복약 기록', ES: 'Registro de Medicación', FR: 'Registre de Médicaments', IT: 'Registro Farmaci', TL: 'Medication Record', ID: 'Catatan Obat', DE: 'Medikamentenaufzeichnung', PT: 'Registro de Medicação', RU: 'Запись лекарств' },
    desc: { EN: 'Japan uses a "medication notebook" (お薬手帳) system — a record of all your prescriptions. Several free apps digitize this. Popular options include EPARKお薬手帳 and Musubi. Pharmacists can scan your app instead of a paper booklet.', JP: '日本では「お薬手帳」制度があり、処方された全薬を記録します。これをデジタル化する無料アプリが複数あります。EPARKお薬手帳やMusubiなどが人気。薬剤師が紙の手帳の代わりにアプリをスキャンできます。', ZH: '日本有"药品手册"（お薬手帳）制度，记录所有处方。多款免费应用可将其数字化，热门选择包括EPARKお薬手帳和Musubi。药剂师可以扫描您的应用代替纸质手册。', 'ZH-T': '日本有"藥品手冊"（お薬手帳）制度，記錄所有處方。多款免費應用可將其數字化，熱門選擇包括EPARKお薬手帳和Musubi。藥劑師可以掃描您的應用代替紙質手冊。', KO: '일본에는 "약 수첩"(お薬手帳) 제도가 있어 모든 처방을 기록합니다. 여러 무료 앱이 이를 디지털화합니다. 인기 옵션으로는 EPARKお薬手帳과 Musubi가 있습니다. 약사가 종이 수첩 대신 앱을 스캔할 수 있습니다.', ES: 'Japón usa el sistema de "cuaderno de medicamentos" (お薬手帳) para registrar todas las recetas. Varias apps gratuitas lo digitalizan. Las populares incluyen EPARKお薬手帳 y Musubi.', FR: 'Le Japon utilise un système de "carnet de médicaments" (お薬手帳). Plusieurs apps gratuites le numérisent. Les populaires incluent EPARKお薬手帳 et Musubi.', IT: 'Il Giappone usa il sistema del "libretto dei farmaci" (お薬手帳). Diverse app gratuite lo digitalizzano. Le popolari includono EPARKお薬手帳 e Musubi.', TL: 'Gumagamit ang Japan ng "medication notebook" (お薬手帳) system. Maraming libreng apps ang nag-digitize nito. Kasama sa popular options ang EPARKお薬手帳 at Musubi.', ID: 'Jepang menggunakan sistem "buku obat" (お薬手帳). Beberapa aplikasi gratis mendigitalkan ini. Pilihan populer termasuk EPARKお薬手帳 dan Musubi.', DE: 'Japan nutzt das "Medikamentenheft"-System (お薬手帳). Mehrere kostenlose Apps digitalisieren es. Beliebte Optionen sind EPARKお薬手帳 und Musubi.', PT: 'O Japão usa o sistema de "caderno de medicamentos" (お薬手帳). Vários apps gratuitos o digitalizam. Opções populares incluem EPARKお薬手帳 e Musubi.', RU: 'В Японии используется система "тетради лекарств" (お薬手帳). Несколько бесплатных приложений её оцифровывают. Популярные варианты — EPARKお薬手帳 и Musubi.' },
    tips: { EN: ['Show your app at every pharmacy visit instead of a paper booklet', 'Helps doctors check for drug interactions', 'Useful if you visit multiple clinics'], JP: ['薬局受診時に紙の手帳の代わりにアプリを見せる', '医師が薬の相互作用を確認するのに役立つ', '複数のクリニックを受診する場合に特に便利'], ZH: ['每次去药局时展示应用而非纸质手册', '帮助医生检查药物相互作用', '如果您去多个诊所，特别有用'], 'ZH-T': ['每次去藥局時展示應用而非紙質手冊', '幫助醫生檢查藥物相互作用', '如果您去多個診所，特別有用'], KO: ['약국 방문 시 종이 수첩 대신 앱을 보여주세요', '의사가 약물 상호작용을 확인하는 데 도움', '여러 클리닉을 방문하는 경우 특히 유용'], ES: ['Muestra tu app en cada visita a la farmacia en lugar del cuaderno', 'Ayuda a los médicos a comprobar interacciones de fármacos', 'Útil si visitas múltiples clínicas'], FR: ['Montrez votre app à chaque visite en pharmacie au lieu du carnet', 'Aide les médecins à vérifier les interactions médicamenteuses', 'Utile si vous visitez plusieurs cliniques'], IT: ['Mostra la tua app ad ogni visita in farmacia invece del libretto', 'Aiuta i medici a verificare le interazioni tra farmaci', 'Utile se visiti più cliniche'], TL: ['Ipakita ang iyong app sa bawat pagbisita sa parmasya sa halip na papel na booklet', 'Nakakatulong sa mga doktor na suriin ang drug interactions', 'Kapaki-pakinabang kung bumibisita sa maraming klinika'], ID: ['Tunjukkan aplikasi Anda di setiap kunjungan apotek alih-alih buku', 'Membantu dokter memeriksa interaksi obat', 'Berguna jika mengunjungi beberapa klinik'], DE: ['App bei jedem Apothekenbesuch zeigen statt Heft', 'Hilft Ärzten, Wechselwirkungen zu prüfen', 'Nützlich wenn mehrere Kliniken besucht werden'], PT: ['Mostre seu app em cada visita à farmácia em vez do caderno', 'Ajuda médicos a verificar interações de medicamentos', 'Útil se você visita múltiplas clínicas'], RU: ['Показывайте приложение при каждом посещении аптеки вместо бумажной тетради', 'Помогает врачам проверять взаимодействие лекарств', 'Полезно при посещении нескольких клиник'] },
  },
  {
    icon: 'photo_camera',
    color: '#374151',
    bg: '#f9fafb',
    name: { EN: 'Pashakarute (パシャカルテ)', JP: 'パシャカルテ', ZH: 'Pashakarute (パシャカルテ)', 'ZH-T': 'Pashakarute (パシャカルテ)', KO: 'Pashakarute (パシャカルテ)', ES: 'Pashakarute (パシャカルテ)', FR: 'Pashakarute (パシャカルテ)', IT: 'Pashakarute (パシャカルテ)', TL: 'Pashakarute (パシャカルテ)', ID: 'Pashakarute (パシャカルテ)', DE: 'Pashakarute (パシャカルテ)', PT: 'Pashakarute (パシャカルテ)', RU: 'Pashakarute (パシャカルテ)' },
    url: 'https://pashakarute.jp/',
    badge: 'iOS · Android · Free',
    category: { EN: 'Medical Records', JP: '診察記録', ZH: '病历记录', 'ZH-T': '病歷記錄', KO: '의료 기록', ES: 'Registros Médicos', FR: 'Dossiers Médicaux', IT: 'Cartelle Cliniche', TL: 'Medical Records', ID: 'Rekam Medis', DE: 'Krankenakten', PT: 'Prontuários Médicos', RU: 'Медицинские записи' },
    desc: { EN: 'Photograph and store your medical records, test results, and prescriptions. Japan does not have a unified digital medical record system — this app fills that gap. Useful when seeing multiple doctors.', JP: '診察記録・検査結果・処方箋を写真で保存するアプリ。日本には統一されたデジタル医療記録システムがないため、このアプリがその役割を果たします。複数の医師にかかる場合に特に便利。', ZH: '拍照保存您的病历、检查结果和处方。日本没有统一的数字医疗记录系统，此应用填补了这一空缺。看多个医生时特别有用。', 'ZH-T': '拍照保存您的病歷、檢查結果和處方。日本沒有統一的數字醫療記錄系統，此應用填補了這一空缺。看多個醫生時特別有用。', KO: '의료 기록, 검사 결과, 처방전을 사진으로 저장합니다. 일본에는 통합된 디지털 의료 기록 시스템이 없어 이 앱이 그 역할을 합니다. 여러 의사를 방문할 때 유용합니다.', ES: 'Fotografía y almacena tus registros médicos, resultados de análisis y recetas. Japón no tiene un sistema unificado de registros médicos digitales — esta app llena ese vacío.', FR: 'Photographiez et stockez vos dossiers médicaux, résultats de tests et ordonnances. Le Japon n\'a pas de système unifié de dossiers médicaux numériques — cette app comble ce manque.', IT: 'Fotografa e archivia le tue cartelle cliniche, risultati dei test e prescrizioni. Il Giappone non ha un sistema unificato di cartelle cliniche digitali — questa app colma questa lacuna.', TL: 'Kumuha ng larawan at i-store ang iyong mga medikal na rekord, resulta ng pagsusuri, at reseta. Walang unified digital medical record system ang Japan — pinupunan ng app na ito ang puwang na iyon.', ID: 'Foto dan simpan catatan medis, hasil tes, dan resep Anda. Jepang tidak memiliki sistem rekam medis digital terpadu — aplikasi ini mengisi celah tersebut.', DE: 'Fotografiere und speichere deine Krankenakten, Testergebnisse und Rezepte. Japan hat kein einheitliches digitales Krankenakten-System — diese App füllt diese Lücke.', PT: 'Fotografe e armazene seus prontuários médicos, resultados de exames e receitas. O Japão não tem um sistema unificado de prontuários médicos digitais — este app preenche essa lacuna.', RU: 'Фотографируйте и храните медицинские записи, результаты анализов и рецепты. В Японии нет единой системы цифровых медицинских записей — это приложение заполняет этот пробел.' },
    tips: { EN: ['Photograph lab results right at the clinic', 'Share records with new doctors easily', 'Helps track changes in test values over time'], JP: ['クリニックで検査結果をすぐ写真に撮って保存', '新しい医師に簡単に記録を共有できる', '検査値の経時的変化を追跡するのに役立つ'], ZH: ['在诊所立即拍摄检查结果', '方便地与新医生分享记录', '帮助追踪检验值随时间的变化'], 'ZH-T': ['在診所立即拍攝檢查結果', '方便地與新醫生分享記錄', '幫助追蹤檢驗值隨時間的變化'], KO: ['클리닉에서 즉시 검사 결과를 사진으로 찍기', '새 의사에게 쉽게 기록 공유', '시간 경과에 따른 검사 수치 변화 추적에 도움'], ES: ['Fotografía los resultados del laboratorio directamente en la clínica', 'Comparte registros con nuevos médicos fácilmente', 'Ayuda a rastrear cambios en valores de análisis con el tiempo'], FR: ['Photographiez les résultats de labo directement à la clinique', 'Partagez facilement les dossiers avec de nouveaux médecins', "Aide à suivre l'évolution des valeurs d'analyses dans le temps"], IT: ['Fotografa i risultati di laboratorio direttamente alla clinica', 'Condividi facilmente le cartelle con nuovi medici', 'Aiuta a monitorare i cambiamenti nei valori dei test nel tempo'], TL: ['Kumuha ng larawan ng mga resulta sa lab mismo sa klinika', 'Madaling ibahagi ang mga rekord sa mga bagong doktor', 'Nakakatulong na subaybayan ang mga pagbabago sa mga halaga ng pagsusuri sa paglipas ng panahon'], ID: ['Foto hasil lab langsung di klinik', 'Bagikan rekam medis dengan dokter baru dengan mudah', 'Membantu melacak perubahan nilai tes dari waktu ke waktu'], DE: ['Laborergebnisse direkt in der Klinik fotografieren', 'Akten einfach mit neuen Ärzten teilen', 'Hilft, Veränderungen der Testwerte im Zeitverlauf zu verfolgen'], PT: ['Fotografe resultados de exames diretamente na clínica', 'Compartilhe prontuários com novos médicos facilmente', 'Ajuda a rastrear mudanças nos valores de exames ao longo do tempo'], RU: ['Фотографируйте результаты анализов прямо в клинике', 'Легко делитесь записями с новыми врачами', 'Помогает отслеживать изменения показателей анализов со временем'] },
  },
]

const NOTE_TITLE = { EN: 'A note on translation apps', JP: '翻訳アプリについて', ZH: '关于翻译应用的说明', 'ZH-T': '關於翻譯應用的說明', KO: '번역 앱에 대한 참고 사항', ES: 'Nota sobre apps de traducción', FR: 'Note sur les apps de traduction', IT: 'Nota sulle app di traduzione', TL: 'Nota sa mga translation apps', ID: 'Catatan tentang aplikasi terjemahan', DE: 'Hinweis zu Übersetzungs-Apps', PT: 'Nota sobre apps de tradução', RU: 'Примечание о приложениях-переводчиках' }
const NOTE_BODY = { EN: 'General translation apps like Google Translate and DeepL also work well in hospitals. However, medical terms can occasionally be mistranslated. VoiceTra is specifically tuned for clinical settings, which may make it more reliable in the exam room.', JP: 'Google翻訳・DeepLなどの汎用翻訳アプリも病院で役立ちます。ただし医療用語は誤訳されることがあります。VoiTraは医療現場専用に設計されているため、診察室ではより信頼性が高い場合があります。', ZH: 'Google翻译、DeepL等通用翻译应用在医院也很有用。但医学术语有时可能被误译。VoiceTra专为临床环境优化，在诊室可能更可靠。', 'ZH-T': 'Google翻譯、DeepL等通用翻譯應用在醫院也很有用。但醫學術語有時可能被誤譯。VoiceTra專為臨床環境優化，在診室可能更可靠。', KO: 'Google 번역, DeepL 등의 일반 번역 앱도 병원에서 잘 작동합니다. 그러나 의학 용어가 가끔 오역될 수 있습니다. VoiceTra는 임상 환경에 특화되어 있어 진료실에서 더 신뢰할 수 있을 수 있습니다.', ES: 'Las apps de traducción general como Google Translate y DeepL también funcionan bien en hospitales. Sin embargo, los términos médicos pueden traducirse incorrectamente a veces. VoiceTra está ajustada específicamente para entornos clínicos.', FR: "Les apps de traduction générales comme Google Translate et DeepL fonctionnent aussi bien dans les hôpitaux. Cependant, les termes médicaux peuvent parfois être mal traduits. VoiceTra est spécifiquement adaptée aux environnements cliniques.", IT: "Le app di traduzione generali come Google Translate e DeepL funzionano bene anche negli ospedali. Tuttavia, i termini medici possono essere occasionalmente tradotti in modo errato. VoiceTra è specificamente ottimizzata per i contesti clinici.", TL: 'Ang mga pangkalahatang translation apps tulad ng Google Translate at DeepL ay gumagana rin nang maayos sa mga ospital. Gayunpaman, ang mga medikal na termino ay maaaring maling isalin. Ang VoiceTra ay partikular na na-tune para sa mga clinical settings.', ID: 'Aplikasi terjemahan umum seperti Google Translate dan DeepL juga bekerja dengan baik di rumah sakit. Namun, istilah medis terkadang bisa salah diterjemahkan. VoiceTra khusus disesuaikan untuk lingkungan klinis.', DE: 'Allgemeine Übersetzungs-Apps wie Google Translate und DeepL funktionieren auch in Krankenhäusern gut. Medizinische Begriffe können aber gelegentlich falsch übersetzt werden. VoiceTra ist speziell auf klinische Umgebungen ausgerichtet.', PT: 'Apps de tradução gerais como Google Translate e DeepL também funcionam bem em hospitais. No entanto, termos médicos podem ser traduzidos incorretamente às vezes. VoiceTra é especificamente otimizada para ambientes clínicos.', RU: 'Общие приложения для перевода, такие как Google Translate и DeepL, также хорошо работают в больницах. Однако медицинские термины иногда могут быть переведены неверно. VoiceTra специально настроена для клинических условий.' }
const OPEN_PAGE = { EN: 'Open official page', JP: '公式ページを開く', ZH: '打开官方页面', 'ZH-T': '打開官方頁面', KO: '공식 페이지 열기', ES: 'Abrir página oficial', FR: 'Ouvrir la page officielle', IT: 'Apri la pagina ufficiale', TL: 'Buksan ang opisyal na pahina', ID: 'Buka halaman resmi', DE: 'Offizielle Seite öffnen', PT: 'Abrir página oficial', RU: 'Открыть официальную страницу' }
const TIPS_LABEL = { EN: 'Tips', JP: '使い方のポイント', ZH: '使用技巧', 'ZH-T': '使用技巧', KO: '팁', ES: 'Consejos', FR: 'Conseils', IT: 'Consigli', TL: 'Mga Tips', ID: 'Tips', DE: 'Tipps', PT: 'Dicas', RU: 'Советы' }

export default function AppsPage() {
  const { lang } = useLang()
  const { isSaved, toggle } = useSaved()
  const saved = isSaved(ITEM.href)

  return (
    <main className="mj-container" style={{ paddingTop: 28, paddingBottom: 40 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
        <Link href="/dashboard" className="page-back" style={{ marginBottom: 0 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 16 }}>arrow_back</span>
          {tr(COMMON.back, lang)}
        </Link>
        <button onClick={() => toggle(ITEM)} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 6, display: 'flex', alignItems: 'center', gap: 4, color: saved ? '#b22620' : '#78716c', fontSize: 12 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 20, fontVariationSettings: saved ? "'FILL' 1" : "'FILL' 0" }}>bookmark</span>
          {saved ? tr(COMMON.saved, lang) : tr(COMMON.save, lang)}
        </button>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6, marginTop: 16 }}>
        <span className="material-symbols-outlined" style={{ fontSize: 22, color: '#b22620', fontVariationSettings: "'FILL' 1" as string }}>apps</span>
        <h1 className="font-headline" style={{ fontSize: 22, fontWeight: 800 }}>{tl(TITLE, lang)}</h1>
      </div>
      <p style={{ fontSize: 13, color: '#5a413d', marginBottom: 28, lineHeight: 1.65 }}>{tl(SUB, lang)}</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {APPS.map((app, i) => {
          const appTips = app.tips[lang as keyof typeof app.tips] ?? app.tips.EN
          return (
            <div key={i} style={{ background: app.bg, borderRadius: 16, padding: '20px', border: `1px solid ${app.color}15`, borderLeft: `3px solid ${app.color}` }}>
              <div style={{ display: 'flex', gap: 14, alignItems: 'flex-start', marginBottom: 12 }}>
                <div style={{ width: 44, height: 44, borderRadius: 12, background: app.color, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <span className="material-symbols-outlined" style={{ fontSize: 24, color: '#fff', fontVariationSettings: "'FILL' 1" as string }}>{app.icon}</span>
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '4px 10px', marginBottom: 2 }}>
                    <p className="font-headline" style={{ fontSize: 15, fontWeight: 800, color: '#1e1b1c' }}>
                      {tl(app.name, lang)}
                    </p>
                    <span style={{ fontSize: 9, color: app.color, background: `${app.color}18`, padding: '2px 8px', borderRadius: 999, fontWeight: 700, whiteSpace: 'nowrap' }}>
                      {tl(app.category, lang)}
                    </span>
                  </div>
                  <p style={{ fontSize: 10, color: '#78716c' }}>{app.badge}</p>
                </div>
              </div>

              <p style={{ fontSize: 13, color: '#374151', lineHeight: 1.7, marginBottom: 14 }}>
                {tl(app.desc, lang)}
              </p>

              <div style={{ background: 'rgba(255,255,255,0.6)', borderRadius: 10, padding: '12px 14px', marginBottom: 10 }}>
                <p className="font-label" style={{ fontSize: 9, fontWeight: 700, color: app.color, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 8 }}>
                  {tl(TIPS_LABEL, lang)}
                </p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {appTips.map((tip, j) => (
                    <div key={j} style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                      <span className="material-symbols-outlined" style={{ fontSize: 13, color: app.color, flexShrink: 0, marginTop: 2 }}>check_circle</span>
                      <p style={{ fontSize: 12, color: '#374151', lineHeight: 1.55 }}>{tip}</p>
                    </div>
                  ))}
                </div>
              </div>
              <a href={app.url} target="_blank" rel="noopener noreferrer"
                style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 14px', background: app.color, color: '#fff', borderRadius: 8, fontSize: 12, fontWeight: 700, textDecoration: 'none' }}>
                <span className="material-symbols-outlined" style={{ fontSize: 14 }}>open_in_new</span>
                {tl(OPEN_PAGE, lang)}
              </a>
            </div>
          )
        })}
      </div>

      <div style={{ marginTop: 28, padding: '16px 18px', background: '#faf2f2', borderRadius: 14, border: '1px solid rgba(178,38,32,0.1)' }}>
        <p className="font-headline" style={{ fontSize: 13, fontWeight: 700, color: '#1e1b1c', marginBottom: 6 }}>
          {tl(NOTE_TITLE, lang)}
        </p>
        <p style={{ fontSize: 12, color: '#5a413d', lineHeight: 1.65 }}>
          {tl(NOTE_BODY, lang)}
        </p>
      </div>
    </main>
  )
}
