'use client'
import Link from 'next/link'
import { useLang } from '../lang-context'
import { useSaved } from '../saved-context'
import { tr, COMMON } from '../translations'

const ITEM = { href: '/dashboard/english-support', title: 'English & Multilingual Support', titleJP: '英語・多言語サポート', icon: 'record_voice_over', color: '#206777' }
function tl(m: Record<string, string>, l: string) { return m[l] ?? m['EN'] }

const TITLE = { EN: 'English & Multilingual Support', JP: '英語・多言語医療サポート', ZH: '英语及多语言医疗支持', 'ZH-T': '英語及多語言醫療支持', KO: '영어 및 다국어 의료 지원', ES: 'Apoyo en Inglés y Multilingüe', FR: 'Soutien Médical Multilingue', IT: 'Supporto Medico Multilingue', TL: 'English at Multilingual Support', ID: 'Dukungan Medis Multibahasa', DE: 'Englischer & mehrsprachiger Medizin-Support', PT: 'Suporte Médico Multilíngue', RU: 'Поддержка на английском и других языках' }
const SUB = { EN: 'Free services and resources for finding English-speaking doctors, translators, and medical help in Japan.', JP: '英語対応医師・通訳・医療サポートを無料で見つけるためのリソース。', ZH: '在日本寻找英语医生、翻译和医疗帮助的免费资源。', 'ZH-T': '在日本尋找英語醫生、翻譯和醫療幫助的免費資源。', KO: '일본에서 영어 의사, 통역사, 의료 지원을 무료로 찾는 리소스.', ES: 'Servicios gratuitos para encontrar médicos angloparlantes, traductores y ayuda médica en Japón.', FR: 'Services gratuits pour trouver des médecins anglophones, des traducteurs et une aide médicale au Japon.', IT: 'Servizi gratuiti per trovare medici di lingua inglese, traduttori e assistenza medica in Giappone.', TL: 'Mga libreng serbisyo para mahanap ang mga doktong nagsasalita ng Ingles, mga tagapagsalin, at tulong medikal sa Japan.', ID: 'Layanan gratis untuk menemukan dokter berbahasa Inggris, penerjemah, dan bantuan medis di Jepang.', DE: 'Kostenlose Dienste für englischsprachige Ärzte, Dolmetscher und medizinische Hilfe in Japan.', PT: 'Serviços gratuitos para encontrar médicos que falam inglês, tradutores e ajuda médica no Japão.', RU: 'Бесплатные ресурсы для поиска англоязычных врачей, переводчиков и медицинской помощи в Японии.' }

const SEC_PHONE = { EN: 'Free Phone Support', JP: '無料電話サポート', ZH: '免费电话支持', 'ZH-T': '免費電話支持', KO: '무료 전화 지원', ES: 'Soporte Telefónico Gratuito', FR: 'Support Téléphonique Gratuit', IT: 'Supporto Telefonico Gratuito', TL: 'Libreng Tulong sa Telepono', ID: 'Dukungan Telepon Gratis', DE: 'Kostenloser Telefon-Support', PT: 'Suporte Telefônico Gratuito', RU: 'Бесплатная телефонная поддержка' }
const SEC_WEB = { EN: 'Websites & Apps', JP: 'ウェブサービス・アプリ', ZH: '网站与应用', 'ZH-T': '網站與應用', KO: '웹사이트 및 앱', ES: 'Sitios Web y Apps', FR: 'Sites Web et Apps', IT: 'Siti Web e App', TL: 'Mga Website at App', ID: 'Situs Web & Aplikasi', DE: 'Websites & Apps', PT: 'Sites e Aplicativos', RU: 'Сайты и приложения' }
const SEC_TIPS = { EN: 'Practical Tips', JP: '実践的なアドバイス', ZH: '实用建议', 'ZH-T': '實用建議', KO: '실용적인 팁', ES: 'Consejos Prácticos', FR: 'Conseils Pratiques', IT: 'Consigli Pratici', TL: 'Mga Praktikal na Tips', ID: 'Tips Praktis', DE: 'Praktische Tipps', PT: 'Dicas Práticas', RU: 'Практические советы' }

const PHONES = [
  {
    icon: 'call', color: '#b22620',
    name: 'AMDA International Medical Information Center',
    number: '03-5285-8088',
    hours: { EN: 'Mon–Fri 9:00–17:00', JP: '月〜金 9:00〜17:00', ZH: '周一至周五 9:00–17:00', 'ZH-T': '週一至週五 9:00–17:00', KO: '월~금 9:00–17:00', ES: 'Lun–Vie 9:00–17:00', FR: 'Lun–Ven 9h00–17h00', IT: 'Lun–Ven 9:00–17:00', TL: 'Lun–Biy 9:00–17:00', ID: 'Sen–Jum 9:00–17:00', DE: 'Mo–Fr 9:00–17:00', PT: 'Seg–Sex 9:00–17:00', RU: 'Пн–Пт 9:00–17:00' },
    langs: { EN: 'English, Chinese, Korean, Spanish, Thai, and more', JP: '英語・中国語・韓国語・スペイン語・タイ語など', ZH: '英语、中文、韩语、西班牙语、泰语等', 'ZH-T': '英語、中文、韓語、西班牙語、泰語等', KO: '영어, 중국어, 한국어, 스페인어, 태국어 등', ES: 'Inglés, chino, coreano, español, tailandés y más', FR: 'Anglais, chinois, coréen, espagnol, thaï et plus', IT: 'Inglese, cinese, coreano, spagnolo, tailandese e altro', TL: 'Ingles, Tsino, Koreano, Espanyol, Thai, at iba pa', ID: 'Inggris, Cina, Korea, Spanyol, Thai, dan lainnya', DE: 'Englisch, Chinesisch, Koreanisch, Spanisch, Thai und mehr', PT: 'Inglês, chinês, coreano, espanhol, tailandês e mais', RU: 'Английский, китайский, корейский, испанский, тайский и другие' },
    desc: { EN: 'Free multilingual medical consultation by phone. Can help find English-speaking doctors near you, explain hospital procedures, and answer insurance questions.', JP: '無料多言語電話医療相談。英語対応医師の紹介・病院手続きの説明・保険の質問に対応。', ZH: '免费多语言电话医疗咨询。可帮助寻找附近的英语医生、解释医院手续并回答保险问题。', 'ZH-T': '免費多語言電話醫療諮詢。可幫助尋找附近的英語醫生、解釋醫院手續並回答保險問題。', KO: '무료 다국어 전화 의료 상담. 근처 영어 의사 찾기, 병원 절차 설명, 보험 질문에 답변해 드립니다.', ES: 'Consulta médica multilingüe gratuita por teléfono. Puede ayudar a encontrar médicos angloparlantes, explicar procedimientos hospitalarios y responder preguntas de seguro.', FR: "Consultation médicale multilingue gratuite par téléphone. Peut aider à trouver des médecins anglophones, expliquer les procédures hospitalières et répondre aux questions d'assurance.", IT: 'Consulenza medica multilingue gratuita per telefono. Può aiutare a trovare medici di lingua inglese, spiegare le procedure ospedaliere e rispondere alle domande assicurative.', TL: 'Libreng multilingual na medikal na konsultasyon sa telepono. Makakatulong sa paghanap ng mga doktong nagsasalita ng Ingles, pagpapaliwanag ng mga proseso sa ospital, at pagsagot sa mga tanong sa insurance.', ID: 'Konsultasi medis multibahasa gratis melalui telepon. Dapat membantu menemukan dokter berbahasa Inggris, menjelaskan prosedur rumah sakit, dan menjawab pertanyaan asuransi.', DE: 'Kostenlose mehrsprachige Medizinberatung per Telefon. Kann bei der Suche nach englischsprachigen Ärzten helfen, Krankenhausverfahren erklären und Versicherungsfragen beantworten.', PT: 'Consulta médica multilíngue gratuita por telefone. Pode ajudar a encontrar médicos que falam inglês, explicar procedimentos hospitalares e responder perguntas sobre seguro.', RU: 'Бесплатная многоязычная медицинская консультация по телефону. Поможет найти англоязычных врачей, объяснить больничные процедуры и ответить на вопросы о страховке.' },
  },
  {
    icon: 'language', color: '#206777',
    name: 'Japan Visitor Hotline (JNTO)',
    number: '050-3816-2787',
    hours: { EN: '24 hours / 365 days', JP: '24時間・365日', ZH: '24小时 / 365天', 'ZH-T': '24小時 / 365天', KO: '24시간 / 365일', ES: '24 horas / 365 días', FR: '24h/24 / 365 jours', IT: '24 ore / 365 giorni', TL: '24 oras / 365 araw', ID: '24 jam / 365 hari', DE: '24 Stunden / 365 Tage', PT: '24 horas / 365 dias', RU: '24 часа / 365 дней' },
    langs: { EN: 'English, Chinese, Korean, Japanese', JP: '英語・中国語・韓国語・日本語', ZH: '英语、中文、韩语、日语', 'ZH-T': '英語、中文、韓語、日語', KO: '영어, 중국어, 한국어, 일본어', ES: 'Inglés, chino, coreano, japonés', FR: 'Anglais, chinois, coréen, japonais', IT: 'Inglese, cinese, coreano, giapponese', TL: 'Ingles, Tsino, Koreano, Hapon', ID: 'Inggris, Cina, Korea, Jepang', DE: 'Englisch, Chinesisch, Koreanisch, Japanisch', PT: 'Inglês, chinês, coreano, japonês', RU: 'Английский, китайский, корейский, японский' },
    desc: { EN: "Japan National Tourism Organization's free hotline. Provides general assistance including medical emergencies, hospital guidance, and interpreter referral for tourists and visitors.", JP: '観光庁の無料ホットライン。医療緊急時の案内・病院案内・通訳紹介に対応。主に観光客向け。', ZH: '日本国家旅游局免费热线。提供包括医疗急救、医院指导和翻译介绍在内的一般援助，主要面向游客。', 'ZH-T': '日本國家旅遊局免費熱線。提供包括醫療急救、醫院指導和翻譯介紹在內的一般援助，主要面向遊客。', KO: '일본 국가관광청 무료 핫라인. 의료 응급 상황, 병원 안내, 통역 소개 등 일반 지원을 제공합니다. 주로 관광객 대상.', ES: 'Línea gratuita de la Organización Nacional de Turismo de Japón. Proporciona asistencia general incluyendo emergencias médicas, orientación hospitalaria y referencia de intérpretes.', FR: "Ligne gratuite de l'Organisation nationale du tourisme du Japon. Fournit une assistance générale pour les urgences médicales, l'orientation hospitalière et les référence d'interprètes.", IT: "Linea gratuita dell'Organizzazione Nazionale del Turismo del Giappone. Fornisce assistenza generale per emergenze mediche, orientamento ospedaliero e riferimento di interpreti.", TL: 'Libreng hotline ng Japan National Tourism Organization. Nagbibigay ng pangkalahatang tulong kabilang ang mga medikal na emergency, gabay sa ospital, at referral ng interpreter.', ID: 'Hotline gratis Organisasi Pariwisata Nasional Jepang. Memberikan bantuan umum termasuk keadaan darurat medis, panduan rumah sakit, dan referral interpreter.', DE: 'Kostenlose Hotline der Nationalen Tourismusorganisation Japans. Bietet allgemeine Unterstützung bei medizinischen Notfällen, Krankenhausführung und Dolmetschervermittlung.', PT: 'Linha gratuita da Organização Nacional de Turismo do Japão. Fornece assistência geral incluindo emergências médicas, orientação hospitalar e encaminhamento de intérpretes.', RU: 'Бесплатная горячая линия Национальной туристической организации Японии. Оказывает общую помощь при медицинских чрезвычайных ситуациях, ориентации в больницах и направлении к переводчикам.' },
  },
  {
    icon: 'psychology', color: '#374151',
    name: 'TELL (Tokyo English Life Line)',
    number: '03-5774-0992',
    hours: { EN: 'Daily 9:00–23:00', JP: '毎日 9:00〜23:00', ZH: '每天 9:00–23:00', 'ZH-T': '每天 9:00–23:00', KO: '매일 9:00–23:00', ES: 'Diario 9:00–23:00', FR: 'Tous les jours 9h00–23h00', IT: 'Ogni giorno 9:00–23:00', TL: 'Araw-araw 9:00–23:00', ID: 'Setiap hari 9:00–23:00', DE: 'Täglich 9:00–23:00', PT: 'Diariamente 9:00–23:00', RU: 'Ежедневно 9:00–23:00' },
    langs: { EN: 'English', JP: '英語', ZH: '英语', 'ZH-T': '英語', KO: '영어', ES: 'Inglés', FR: 'Anglais', IT: 'Inglese', TL: 'Ingles', ID: 'Inggris', DE: 'Englisch', PT: 'Inglês', RU: 'Английский' },
    desc: { EN: 'English-language counseling and mental health support. For anyone in Japan feeling isolated, anxious, or struggling. Not only for Tokyo residents.', JP: '英語でのカウンセリング・メンタルヘルスサポート。東京以外の方も利用可能。', ZH: '英语心理咨询和心理健康支持。面向任何在日本感到孤立、焦虑或困难的人。不仅限于东京居民。', 'ZH-T': '英語心理諮詢和心理健康支持。面向任何在日本感到孤立、焦慮或困難的人。不僅限於東京居民。', KO: '영어 상담 및 정신 건강 지원. 일본에서 고립감, 불안감, 또는 어려움을 느끼는 모든 사람을 위한 것입니다. 도쿄 거주자만 해당되지 않습니다.', ES: 'Asesoramiento en inglés y apoyo de salud mental. Para cualquier persona en Japón que se sienta aislada, ansiosa o con dificultades. No solo para residentes de Tokio.', FR: "Conseil en anglais et soutien en santé mentale. Pour toute personne au Japon se sentant isolée, anxieuse ou en difficulté. Pas seulement pour les résidents de Tokyo.", IT: 'Consulenza in inglese e supporto alla salute mentale. Per chiunque in Giappone si senta isolato, ansioso o in difficoltà. Non solo per i residenti di Tokyo.', TL: 'Konseling sa Ingles at suporta sa kalusugang pangkaisipan. Para sa sinumang nasa Japan na nakakaramdam ng pagiging nag-iisa, pagkabalisa, o kahirapan. Hindi lamang para sa mga taga-Tokyo.', ID: 'Konseling bahasa Inggris dan dukungan kesehatan mental. Untuk siapa saja di Jepang yang merasa terisolasi, cemas, atau kesulitan. Tidak hanya untuk penduduk Tokyo.', DE: 'Englischsprachige Beratung und psychische Gesundheitsunterstützung. Für alle in Japan, die sich isoliert, ängstlich oder überfordert fühlen. Nicht nur für Tokio-Bewohner.', PT: 'Aconselhamento em inglês e suporte à saúde mental. Para qualquer pessoa no Japão que se sinta isolada, ansiosa ou com dificuldades. Não apenas para residentes de Tóquio.', RU: 'Консультации на английском языке и поддержка психического здоровья. Для всех, кто в Японии чувствует себя изолированным, тревожным или испытывает трудности. Не только для жителей Токио.' },
  },
  {
    icon: 'volunteer_activism', color: '#7a5700',
    name: 'Yorisoi Hotline (よりそいホットライン)',
    number: '0120-279-338',
    hours: { EN: '24 hours / 365 days — FREE', JP: '24時間・365日・無料', ZH: '24小时 / 365天 — 免费', 'ZH-T': '24小時 / 365天 — 免費', KO: '24시간 / 365일 — 무료', ES: '24 horas / 365 días — GRATIS', FR: '24h/24 / 365 jours — GRATUIT', IT: '24 ore / 365 giorni — GRATUITO', TL: '24 oras / 365 araw — LIBRE', ID: '24 jam / 365 hari — GRATIS', DE: '24 Stunden / 365 Tage — KOSTENLOS', PT: '24 horas / 365 dias — GRATUITO', RU: '24 часа / 365 дней — БЕСПЛАТНО' },
    langs: { EN: 'Japanese, English, Chinese, Korean, and more via interpreter', JP: '日本語・英語・中国語・韓国語など（通訳経由）', ZH: '日语、英语、中文、韩语等（通过口译员）', 'ZH-T': '日語、英語、中文、韓語等（通過口譯員）', KO: '일본어, 영어, 중국어, 한국어 등 (통역 경유)', ES: 'Japonés, inglés, chino, coreano y más vía intérprete', FR: 'Japonais, anglais, chinois, coréen et plus via interprète', IT: 'Giapponese, inglese, cinese, coreano e altro tramite interprete', TL: 'Hapon, Ingles, Tsino, Koreano, at iba pa sa pamamagitan ng interpreter', ID: 'Jepang, Inggris, Cina, Korea, dan lainnya melalui interpreter', DE: 'Japanisch, Englisch, Chinesisch, Koreanisch und mehr über Dolmetscher', PT: 'Japonês, inglês, chinês, coreano e mais via intérprete', RU: 'Японский, английский, китайский, корейский и другие через переводчика' },
    desc: { EN: 'Crisis support and general counseling. Especially useful if you are in distress or having mental health difficulties. Multilingual interpreters connected on the line.', JP: '危機・精神的つらさへの相談窓口。多言語通訳を電話回線につなぐ形で対応。', ZH: '危机支持和一般咨询。如果您处于困境或有心理健康困难，特别有用。多语言口译员接入通话。', 'ZH-T': '危機支持和一般諮詢。如果您處於困境或有心理健康困難，特別有用。多語言口譯員接入通話。', KO: '위기 지원 및 일반 상담. 고통받거나 정신 건강에 어려움이 있는 경우 특히 유용합니다. 전화에 다국어 통역사 연결.', ES: 'Apoyo en crisis y asesoramiento general. Especialmente útil si está en apuros o tiene dificultades de salud mental. Intérpretes multilingües conectados en la línea.', FR: 'Soutien en crise et conseil général. Particulièrement utile si vous êtes en détresse ou avez des difficultés de santé mentale. Des interprètes multilingues sont connectés sur la ligne.', IT: 'Supporto in crisi e consulenza generale. Particolarmente utile se sei in difficoltà o hai problemi di salute mentale. Interpreti multilingue connessi sulla linea.', TL: 'Suporta sa krisis at pangkalahatang konsultasyon. Lalo itong kapaki-pakinabang kung nasa pagdurusa o may kahirapan sa kalusugang pangkaisipan. Mga multilingual na interpreter na nakakonekta sa linya.', ID: 'Dukungan krisis dan konseling umum. Sangat berguna jika Anda dalam kesulitan atau memiliki masalah kesehatan mental. Interpreter multibahasa terhubung di saluran telepon.', DE: 'Krisenunterstützung und allgemeine Beratung. Besonders nützlich, wenn Sie in Not sind oder psychische Gesundheitsprobleme haben. Mehrsprachige Dolmetscher sind in der Leitung verbunden.', PT: 'Apoio em crises e aconselhamento geral. Especialmente útil se estiver em sofrimento ou com dificuldades de saúde mental. Intérpretes multilíngues conectados na linha.', RU: 'Кризисная поддержка и общее консультирование. Особенно полезно, если вы в беде или испытываете трудности с психическим здоровьем. Многоязычные переводчики подключены к линии.' },
  },
]

const WEBSITES = [
  { icon: 'search', color: '#206777', name: 'HIMAWARI (ひまわり)', url: 'himawari.metro.tokyo.lg.jp', desc: { EN: "Tokyo Metropolitan Government's multilingual medical consultation. Find English-speaking hospitals and clinics in Tokyo.", JP: '東京都の多言語医療相談。英語対応病院・クリニックを検索できる。', ZH: '东京都政府的多语言医疗咨询。可找到东京的英语医院和诊所。', 'ZH-T': '東京都政府的多語言醫療諮詢。可找到東京的英語醫院和診所。', KO: '도쿄도 정부의 다국어 의료 상담. 도쿄의 영어 병원 및 클리닉을 찾을 수 있습니다.', ES: 'Consulta médica multilingüe del Gobierno Metropolitano de Tokio. Encuentra hospitales y clínicas de habla inglesa en Tokio.', FR: 'Consultation médicale multilingue du Gouvernement Métropolitain de Tokyo. Trouvez des hôpitaux et cliniques anglophones à Tokyo.', IT: 'Consulenza medica multilingue del Governo Metropolitano di Tokyo. Trova ospedali e cliniche di lingua inglese a Tokyo.', TL: 'Multilingual na medikal na konsultasyon ng Pamahalaan ng Lungsod ng Tokyo. Hanapin ang mga ospital at klinika na nagsasalita ng Ingles sa Tokyo.', ID: 'Konsultasi medis multibahasa Pemerintah Metropolit Tokyo. Temukan rumah sakit dan klinik berbahasa Inggris di Tokyo.', DE: 'Mehrsprachige medizinische Beratung der Metropolitanregierung Tokio. Finden Sie englischsprachige Krankenhäuser und Kliniken in Tokio.', PT: 'Consulta médica multilíngue do Governo Metropolitano de Tóquio. Encontre hospitais e clínicas de língua inglesa em Tóquio.', RU: 'Многоязычная медицинская консультация правительства Токийской митрополии. Найдите больницы и клиники с английским языком в Токио.' } },
  { icon: 'local_hospital', color: '#b22620', name: 'MIC Medical Interpreter Network', url: 'mic-japan.org', desc: { EN: 'Non-profit network of certified medical interpreters across Japan. Request a certified interpreter for hospital appointments.', JP: '全国の認定医療通訳者ネットワーク。病院予約時の認定通訳を手配できる。', ZH: '全日本认证医疗口译员非营利网络。可为医院预约安排认证口译员。', 'ZH-T': '全日本認證醫療口譯員非營利網絡。可為醫院預約安排認證口譯員。', KO: '일본 전국 인증 의료 통역사 비영리 네트워크. 병원 예약을 위한 인증 통역사를 요청할 수 있습니다.', ES: 'Red sin fines de lucro de intérpretes médicos certificados en Japón. Solicita un intérprete certificado para citas hospitalarias.', FR: "Réseau à but non lucratif d'interprètes médicaux certifiés à travers le Japon. Demandez un interprète certifié pour des rendez-vous à l'hôpital.", IT: 'Rete non-profit di interpreti medici certificati in tutto il Giappone. Richiedi un interprete certificato per gli appuntamenti ospedalieri.', TL: 'Non-profit na network ng mga certified medical interpreter sa buong Japan. Humiling ng certified interpreter para sa mga appointment sa ospital.', ID: 'Jaringan nirlaba interpreter medis bersertifikat di seluruh Jepang. Minta interpreter bersertifikat untuk janji rumah sakit.', DE: 'Gemeinnütziges Netzwerk zertifizierter medizinischer Dolmetscher in ganz Japan. Fordern Sie einen zertifizierten Dolmetscher für Krankenhausgespräche an.', PT: 'Rede sem fins lucrativos de intérpretes médicos certificados em todo o Japão. Solicite um intérprete certificado para consultas hospitalares.', RU: 'Некоммерческая сеть сертифицированных медицинских переводчиков по всей Японии. Запросите сертифицированного переводчика для посещения больницы.' } },
  { icon: 'medical_information', color: '#7a5700', name: 'JMIP (Japan Medical Service Accreditation)', url: 'jmip.jp', desc: { EN: 'Searchable list of hospitals certified for international patient care. These hospitals have multilingual staff and foreigner-friendly procedures.', JP: '外国人患者受け入れ認証病院リスト。多言語スタッフが在籍し、外国人対応が充実。', ZH: '可搜索的国际患者医疗认证医院列表。这些医院拥有多语言工作人员和对外国人友好的流程。', 'ZH-T': '可搜索的國際患者醫療認證醫院列表。這些醫院擁有多語言工作人員和對外國人友好的流程。', KO: '국제 환자 의료를 위해 인증된 병원의 검색 가능한 목록. 이 병원들에는 다국어 직원이 있고 외국인 친화적인 절차가 마련되어 있습니다.', ES: 'Lista de hospitales certificados para atención de pacientes internacionales. Tienen personal multilingüe y procedimientos amigables para extranjeros.', FR: "Liste consultable d'hôpitaux certifiés pour les soins aux patients internationaux. Ces hôpitaux ont du personnel multilingue et des procédures adaptées aux étrangers.", IT: 'Lista consultabile di ospedali certificati per le cure ai pazienti internazionali. Questi ospedali hanno personale multilingue e procedure adatte agli stranieri.', TL: 'Listahan ng mga ospital na certified para sa international patient care. Ang mga ospital na ito ay may multilingual na kawani at mga prosedurong palakaibigan sa mga dayuhan.', ID: 'Daftar rumah sakit yang tersertifikasi untuk perawatan pasien internasional. Rumah sakit ini memiliki staf multibahasa dan prosedur ramah orang asing.', DE: 'Suchbare Liste von Krankenhäusern mit Zertifizierung für internationale Patienten. Diese Krankenhäuser haben mehrsprachiges Personal und ausländerfreundliche Abläufe.', PT: 'Lista pesquisável de hospitais certificados para atendimento de pacientes internacionais. Esses hospitais têm equipe multilíngue e procedimentos amigáveis para estrangeiros.', RU: 'Поисковый список больниц, сертифицированных для оказания помощи иностранным пациентам. В этих больницах есть многоязычный персонал и процедуры, удобные для иностранцев.' } },
  { icon: 'translate', color: '#374151', name: 'VoiceTra (ボイストラ)', url: 'app download', desc: { EN: "Free medical translation app by NICT (Japan's national research institute). Supports 31 languages. Specifically designed for medical consultations in Japan.", JP: '情報通信研究機構（NICT）の無料医療翻訳アプリ。31言語対応。日本の医療現場向けに設計。', ZH: 'NICT（日本国家研究机构）开发的免费医疗翻译应用。支持31种语言，专为日本医疗问诊设计。', 'ZH-T': 'NICT（日本國家研究機構）開發的免費醫療翻譯應用。支持31種語言，專為日本醫療問診設計。', KO: 'NICT(일본 국가 연구 기관)의 무료 의료 번역 앱. 31개 언어 지원. 일본 의료 상담을 위해 특별히 설계됨.', ES: 'App de traducción médica gratuita del NICT (instituto de investigación nacional de Japón). Soporta 31 idiomas. Diseñada específicamente para consultas médicas en Japón.', FR: "Application de traduction médicale gratuite du NICT (Institut national de recherche du Japon). Supporte 31 langues. Conçue spécifiquement pour les consultations médicales au Japon.", IT: "App di traduzione medica gratuita del NICT (istituto di ricerca nazionale del Giappone). Supporta 31 lingue. Progettata specificamente per le consultazioni mediche in Giappone.", TL: 'Libreng medical translation app ng NICT (pambansang research institute ng Japan). Sumusuporta ng 31 na wika. Partikular na dinisenyo para sa mga medikal na konsultasyon sa Japan.', ID: 'Aplikasi terjemahan medis gratis dari NICT (lembaga penelitian nasional Jepang). Mendukung 31 bahasa. Dirancang khusus untuk konsultasi medis di Jepang.', DE: 'Kostenlose medizinische Übersetzungs-App des NICT (nationales Forschungsinstitut Japans). Unterstützt 31 Sprachen. Speziell für medizinische Beratungen in Japan konzipiert.', PT: 'App de tradução médica gratuita do NICT (instituto de pesquisa nacional do Japão). Suporta 31 idiomas. Projetado especificamente para consultas médicas no Japão.', RU: 'Бесплатное медицинское приложение для перевода от NICT (национальный исследовательский институт Японии). Поддерживает 31 язык. Специально разработано для медицинских консультаций в Японии.' } },
]

const TIPS: Record<string, string[]> = {
  EN: ['Before your appointment, write your symptoms in Japanese using the Phrases page in this app.','Search Google Maps for "English speaking clinic [your city]" or "インターナショナルクリニック" to find foreigner-friendly facilities.','University hospitals in major cities (Tokyo, Osaka, Kyoto, Nagoya) often have international patient departments with English-speaking staff.','Use Google Translate\'s camera mode to read forms and medicine packaging in real time.','If using a hospital interpreter service, book it in advance — same-day interpretation is not always available.'],
  JP: ['受診前にこのアプリのフレーズ集を使って症状を日本語で書いておきましょう。','Googleマップで「英語対応 クリニック [都市名]」または「インターナショナルクリニック」で外国人対応の施設を探せます。','東京・大阪・京都・名古屋などの大都市の大学病院には英語スタッフ常駐の国際診療部門があることが多い。','Google翻訳のカメラ機能で書類や薬のパッケージをリアルタイムで読み取れます。','病院の通訳サービスを利用する場合は事前に予約を。当日対応は難しい場合があります。'],
  ZH: ['预约前，使用本应用的短语页面，用日语写下您的症状。','在谷歌地图搜索"English speaking clinic [您的城市]"或"インターナショナルクリニック"，寻找对外国人友好的设施。','主要城市（东京、大阪、京都、名古屋）的大学医院通常有英语工作人员的国际患者部门。','使用谷歌翻译的相机模式，实时阅读表格和药品包装。','使用医院口译服务时，请提前预约——当天口译并非总是可用。'],
  'ZH-T': ['預約前，使用本應用的短語頁面，用日語寫下您的症狀。','在谷歌地圖搜索"English speaking clinic [您的城市]"或"インターナショナルクリニック"，尋找對外國人友好的設施。','主要城市（東京、大阪、京都、名古屋）的大學醫院通常有英語工作人員的國際患者部門。','使用谷歌翻譯的相機模式，即時閱讀表格和藥品包裝。','使用醫院口譯服務時，請提前預約——當天口譯並非總是可用。'],
  KO: ['예약 전, 이 앱의 구문 페이지를 사용하여 일본어로 증상을 작성하세요.','구글 맵에서 "English speaking clinic [도시]" 또는 "インターナショナルクリニック"를 검색하여 외국인 친화적 시설을 찾으세요.','도쿄, 오사카, 교토, 나고야 등 대도시 대학병원에는 영어 직원이 있는 국제 환자 부서가 있는 경우가 많습니다.','구글 번역의 카메라 모드를 사용하여 양식과 약품 포장을 실시간으로 읽으세요.','병원 통역 서비스를 이용하려면 미리 예약하세요 — 당일 통역은 항상 가능하지 않습니다.'],
  ES: ['Antes de su cita, escriba sus síntomas en japonés usando la página de Frases de esta app.','Busque en Google Maps "English speaking clinic [su ciudad]" o "インターナショナルクリニック" para encontrar instalaciones amigables para extranjeros.','Los hospitales universitarios en ciudades principales (Tokio, Osaka, Kyoto, Nagoya) a menudo tienen departamentos de pacientes internacionales con personal angloparlante.','Use el modo de cámara de Google Translate para leer formularios y empaques de medicamentos en tiempo real.','Si usa el servicio de intérprete del hospital, resérvelo con anticipación — la interpretación el mismo día no siempre está disponible.'],
  FR: ['Avant votre rendez-vous, écrivez vos symptômes en japonais en utilisant la page Phrases de cette application.','Cherchez sur Google Maps "English speaking clinic [votre ville]" ou "インターナショナルクリニック" pour trouver des établissements adaptés aux étrangers.','Les hôpitaux universitaires dans les grandes villes (Tokyo, Osaka, Kyoto, Nagoya) ont souvent des départements patients internationaux avec du personnel anglophone.','Utilisez le mode caméra de Google Translate pour lire des formulaires et des emballages de médicaments en temps réel.','Si vous utilisez le service d\'interprète de l\'hôpital, réservez-le à l\'avance — l\'interprétation le jour même n\'est pas toujours disponible.'],
  IT: ["Prima del suo appuntamento, scrivi i tuoi sintomi in giapponese usando la pagina Frasi di questa app.","Cerca su Google Maps 'English speaking clinic [la tua città]' o 'インターナショナルクリニック' per trovare strutture adatte agli stranieri.","Gli ospedali universitari nelle principali città (Tokyo, Osaka, Kyoto, Nagoya) spesso hanno reparti per pazienti internazionali con personale di lingua inglese.",'Usa la modalità fotocamera di Google Translate per leggere moduli e confezioni di farmaci in tempo reale.',"Se usi il servizio di interprete dell'ospedale, prenotalo in anticipo — l'interpretazione lo stesso giorno non è sempre disponibile."],
  TL: ['Bago ang iyong appointment, isulat ang iyong mga sintomas sa Japanese gamit ang Phrases page sa app na ito.','Maghanap sa Google Maps ng "English speaking clinic [iyong lungsod]" o "インターナショナルクリニック" para mahanap ang mga pasilidad na palakaibigan sa mga dayuhan.','Ang mga university hospital sa malalaking lungsod (Tokyo, Osaka, Kyoto, Nagoya) ay madalas na may international patient department na may mga kawaning nagsasalita ng Ingles.','Gamitin ang camera mode ng Google Translate para basahin ang mga form at packaging ng gamot sa real time.','Kung gagamitin ang hospital interpreter service, mag-book nang maaga — ang same-day interpretation ay hindi palaging available.'],
  ID: ['Sebelum janji, tuliskan gejala Anda dalam bahasa Jepang menggunakan halaman Frasa di aplikasi ini.','Cari di Google Maps "English speaking clinic [kota Anda]" atau "インターナショナルクリニック" untuk menemukan fasilitas ramah orang asing.','Rumah sakit universitas di kota-kota besar (Tokyo, Osaka, Kyoto, Nagoya) sering memiliki departemen pasien internasional dengan staf berbahasa Inggris.','Gunakan mode kamera Google Translate untuk membaca formulir dan kemasan obat secara real time.','Jika menggunakan layanan interpreter rumah sakit, pesan lebih awal — interpretasi di hari yang sama tidak selalu tersedia.'],
  DE: ['Vor Ihrem Termin schreiben Sie Ihre Symptome auf Japanisch mit der Phrasen-Seite dieser App.','Suchen Sie bei Google Maps nach "English speaking clinic [Ihre Stadt]" oder "インターナショナルクリニック" für ausländerfreundliche Einrichtungen.','Universitätskrankenhäuser in großen Städten (Tokio, Osaka, Kyoto, Nagoya) haben oft internationale Patientenabteilungen mit englischsprachigem Personal.','Nutzen Sie den Kameramodus von Google Translate, um Formulare und Medikamentenpackungen in Echtzeit zu lesen.','Wenn Sie den Krankenhausdolmetscher-Service nutzen, buchen Sie ihn im Voraus — same-day-Dolmetschen ist nicht immer verfügbar.'],
  PT: ['Antes da consulta, escreva seus sintomas em japonês usando a página de Frases deste app.','Pesquise no Google Maps "English speaking clinic [sua cidade]" ou "インターナショナルクリニック" para encontrar instalações amigáveis para estrangeiros.','Hospitais universitários nas principais cidades (Tóquio, Osaka, Kyoto, Nagoya) frequentemente têm departamentos de pacientes internacionais com equipe que fala inglês.','Use o modo de câmera do Google Translate para ler formulários e embalagens de medicamentos em tempo real.','Se usar o serviço de intérprete do hospital, reserve com antecedência — a interpretação no mesmo dia nem sempre está disponível.'],
  RU: ['Перед приёмом запишите свои симптомы на японском с помощью раздела «Фразы» этого приложения.','Ищите в Google Maps "English speaking clinic [ваш город]" или "インターナショナルクリニック" для нахождения учреждений, friendly для иностранцев.','Университетские больницы в крупных городах (Токио, Осака, Киото, Нагоя) часто имеют отделения для иностранных пациентов с англоязычным персоналом.','Используйте режим камеры Google Translate для чтения форм и упаковок лекарств в реальном времени.','При использовании больничного переводчика бронируйте заранее — переводчик в день обращения доступен не всегда.'],
}

export default function EnglishSupportPage() {
  const { lang } = useLang()
  const { isSaved, toggle } = useSaved()
  const saved = isSaved(ITEM.href)
  const tips = TIPS[lang] ?? TIPS.EN

  return (
    <main className="mj-container" style={{ paddingTop: 28, paddingBottom: 40 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
        <Link href="/dashboard" className="page-back" style={{ marginBottom: 0 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 16 }}>arrow_back</span>
          {tr(COMMON.back, lang)}
        </Link>
        <button onClick={() => toggle(ITEM)} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 6, display: 'flex', alignItems: 'center', gap: 4, color: saved ? '#b22620' : '#78716c', fontSize: 12 }}>
          <span className="material-symbols-outlined" style={{ fontSize: 20, fontVariationSettings: saved ? "'FILL' 1" : "'FILL' 0" }}>bookmark</span>
          {saved ? tr(COMMON.saved, lang) : tr(COMMON.save, lang)}
        </button>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6, marginTop: 16 }}>
        <span className="material-symbols-outlined" style={{ fontSize: 22, color: '#206777', fontVariationSettings: "'FILL' 1" as string }}>record_voice_over</span>
        <h1 className="font-headline" style={{ fontSize: 22, fontWeight: 800 }}>{tl(TITLE, lang)}</h1>
      </div>
      <p style={{ fontSize: 13, color: '#5a413d', marginBottom: 28 }}>{tl(SUB, lang)}</p>

      {/* Phone lines */}
      <section style={{ marginBottom: 32 }}>
        <h2 className="font-headline" style={{ fontSize: 15, fontWeight: 700, marginBottom: 16 }}>
          {tl(SEC_PHONE, lang)}
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {PHONES.map((p, i) => (
            <div key={i} style={{ background: '#fff', borderRadius: 14, padding: '18px', border: '1px solid rgba(226,190,186,0.2)', borderLeft: `3px solid ${p.color}` }}>
              <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start', marginBottom: 10 }}>
                <div style={{ width: 38, height: 38, borderRadius: 10, background: p.color, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <span className="material-symbols-outlined" style={{ fontSize: 20, color: '#fff', fontVariationSettings: "'FILL' 1" as string }}>{p.icon}</span>
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p className="font-headline" style={{ fontSize: 13, fontWeight: 700, color: '#1e1b1c', marginBottom: 2 }}>{p.name}</p>
                  <a href={`tel:${p.number.replace(/-/g, '')}`} style={{ fontSize: 18, fontWeight: 900, color: p.color, fontFamily: 'Plus Jakarta Sans, sans-serif', textDecoration: 'none', display: 'block', marginBottom: 4 }}>{p.number}</a>
                </div>
              </div>
              <p style={{ fontSize: 13, color: '#5a413d', lineHeight: 1.65, marginBottom: 10 }}>{tl(p.desc, lang)}</p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                <span style={{ fontSize: 11, color: '#78716c', display: 'flex', alignItems: 'center', gap: 4 }}>
                  <span className="material-symbols-outlined" style={{ fontSize: 13 }}>schedule</span>
                  {tl(p.hours, lang)}
                </span>
                <span style={{ fontSize: 11, color: '#78716c', display: 'flex', alignItems: 'center', gap: 4 }}>
                  <span className="material-symbols-outlined" style={{ fontSize: 13 }}>translate</span>
                  {tl(p.langs, lang)}
                </span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Websites & apps */}
      <section style={{ marginBottom: 32 }}>
        <h2 className="font-headline" style={{ fontSize: 15, fontWeight: 700, marginBottom: 14 }}>
          {tl(SEC_WEB, lang)}
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {WEBSITES.map((w, i) => (
            <div key={i} style={{ background: '#fff', borderRadius: 12, padding: '14px 16px', border: '1px solid rgba(226,190,186,0.2)', display: 'flex', gap: 12, alignItems: 'flex-start' }}>
              <div style={{ width: 36, height: 36, borderRadius: 10, background: w.color, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <span className="material-symbols-outlined" style={{ fontSize: 18, color: '#fff', fontVariationSettings: "'FILL' 1" as string }}>{w.icon}</span>
              </div>
              <div>
                <p className="font-headline" style={{ fontSize: 13, fontWeight: 700, color: '#1e1b1c', marginBottom: 2 }}>{w.name}</p>
                <p style={{ fontSize: 11, color: w.color, marginBottom: 5 }}>{w.url}</p>
                <p style={{ fontSize: 12, color: '#5a413d', lineHeight: 1.6 }}>{tl(w.desc, lang)}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Practical tips */}
      <section>
        <h2 className="font-headline" style={{ fontSize: 15, fontWeight: 700, marginBottom: 12 }}>
          {tl(SEC_TIPS, lang)}
        </h2>
        <div style={{ background: '#faf2f2', borderRadius: 14, padding: '18px 20px', border: '1px solid rgba(226,190,186,0.2)' }}>
          {tips.map((tip, i) => (
            <div key={i} style={{ display: 'flex', gap: 10, marginBottom: i < tips.length - 1 ? 10 : 0, alignItems: 'flex-start' }}>
              <span className="material-symbols-outlined" style={{ fontSize: 15, color: '#206777', flexShrink: 0, marginTop: 2 }}>arrow_right</span>
              <p style={{ fontSize: 13, color: '#5a413d', lineHeight: 1.6 }}>{tip}</p>
            </div>
          ))}
        </div>
      </section>
    </main>
  )
}
