type L = Record<string, string>

export function tr(map: L, lang: string): string {
  return map[lang] ?? map['EN']
}

// BCP47 code 'yue' は広東語専用コード。zh-HK は繁体字HKを指すが広東語保証なし。
// 本プロジェクトは lang-context で 'YUE' キーを採用しているためそれに統一する。
const L = (EN: string, JP: string, ZH: string, ZHT: string, KO: string, ES: string, FR: string, IT: string, TL: string, ID: string, DE: string, PT: string, RU: string, YUE: string): L =>
  ({ EN, JP, ZH, 'ZH-T': ZHT, KO, ES, FR, IT, TL, ID, DE, PT, RU, YUE })

export const COMMON = {
  back:      L('Back to Home','ホームに戻る','返回首页','返回首頁','홈으로 돌아가기','Volver al inicio','Retour à l\'accueil','Torna alla home','Bumalik sa Home','Kembali ke Beranda','Zurück zur Startseite','Voltar ao início','На главную','返回主頁'),
  save:      L('Save','保存する','收藏','收藏','저장','Guardar','Enregistrer','Salva','I-save','Simpan','Speichern','Salvar','Сохранить','儲存'),
  saved:     L('Saved','保存済み','已收藏','已收藏','저장됨','Guardado','Enregistré','Salvato','Nai-save','Tersimpan','Gespeichert','Salvo','Сохранено','已儲存'),
  unsave:    L('Remove','保存解除','取消收藏','取消收藏','저장 취소','Quitar','Supprimer','Rimuovi','Alisin','Hapus','Entfernen','Remover','Убрать','移除'),
  tip:       L('Tip','ヒント','提示','提示','팁','Consejo','Conseil','Consiglio','Tip','Tips','Tipp','Dica','Совет','貼士'),
  free:      L('FREE','無料','免費','免費','무료','GRATIS','GRATUIT','GRATIS','LIBRE','GRATIS','KOSTENLOS','GRÁTIS','БЕСПЛАТНО','免費'),
  urgent:    L('URGENT','緊急','紧急','緊急','긴급','URGENTE','URGENT','URGENTE','URGENT','MENDESAK','DRINGEND','URGENTE','СРОЧНО','緊急'),
  hours:     L('Hours','受付時間','营业时间','營業時間','운영 시간','Horario','Horaires','Orari','Oras','Jam Operasional','Öffnungszeiten','Horário','Часы работы','開放時間'),
  for:       L('For','対象者','适用人群','適用人群','대상','Para','Pour','Per','Para sa','Untuk','Für','Para','Для','適用對象'),
  languages: L('Languages','対応言語','语言','語言','언어','Idiomas','Langues','Lingue','Mga Wika','Bahasa','Sprachen','Idiomas','Языки','語言'),
}

export const AMBULANCE = {
  title:      L('Ambulance Guide','救急ガイド','救护车指南','救護車指南','구급차 가이드','Guía de Ambulancia','Guide Ambulance','Guida Ambulanza','Gabay sa Ambulansya','Panduan Ambulans','Rettungswagen-Guide','Guia de Ambulância','Руководство по скорой помощи','救護車指南'),
  subtitle:   L('When and how to call an ambulance in Japan.','日本での救急車の呼び方と基準。','在日本何时以及如何叫救护车。','在日本何時及如何叫救護車。','일본에서 구급차를 부르는 방법과 기준.','Cuándo y cómo llamar a una ambulancia en Japón.','Quand et comment appeler une ambulance au Japon.','Quando e come chiamare un\'ambulanza in Giappone.','Kailan at paano tumawag ng ambulansya sa Japan.','Kapan dan bagaimana memanggil ambulans di Jepang.','Wann und wie man in Japan einen Krankenwagen ruft.','Quando e como chamar uma ambulância no Japão.','Когда и как вызвать скорую помощь в Японии.','喺日本點樣叫救護車，同埋幾時叫救護車。'),
  emergency:  L('Emergency Number','緊急番号','紧急电话','緊急電話','긴급 번호','Número de Emergencia','Numéro d\'urgence','Numero di Emergenza','Numero ng Emergency','Nomor Darurat','Notrufnummer','Número de Emergência','Номер скорой помощи','緊急電話'),
  freeCall:   L('Ambulance & Fire — 24 hours, free to call','救急・消防 — 24時間、無料','救护车及消防 — 24小时，免费拨打','救護車及消防 — 24小時，免費撥打','구급차 및 소방 — 24시간 무료','Ambulancia y Bomberos — 24 horas, llamada gratuita','Ambulance et pompiers — 24h, appel gratuit','Ambulanza e Vigili del Fuoco — 24 ore, gratuito','Ambulansya at Bumbero — 24 oras, libre','Ambulans & Pemadam — 24 jam, gratis','Rettungswagen & Feuerwehr — 24h, kostenlos','Ambulância e Bombeiros — 24h, gratuito','Скорая и пожарные — 24 часа, бесплатно','救護車及消防 — 24小時，免費撥打'),
  callFor:    L('Call 119 Immediately For:','今すぐ119番を呼ぶべき状況:','以下情况立即拨打119:','以下情況立即撥打119:','즉시 119에 전화해야 하는 상황:','Llame al 119 inmediatamente si:','Appelez le 119 immédiatement si:','Chiama il 119 immediatamente se:','Tumawag ng 119 agad kung:','Hubungi 119 segera untuk:','Rufen Sie sofort 119 an bei:','Ligue imediatamente para 119 se:','Немедленно вызовите 119 при:','以下情況請即撥打119：'),
  whatHappens:L('What Happens When You Call 119','119番に電話したらどうなるか','拨打119后会发生什么','撥打119後會發生什麼','119에 전화하면 어떻게 되나요','Qué pasa cuando llamas al 119','Que se passe-t-il quand vous appelez le 119','Cosa succede quando chiami il 119','Ano ang mangyayari kapag tumawag ng 119','Yang Terjadi Saat Menghubungi 119','Was passiert, wenn Sie 119 anrufen','O que acontece quando você liga para o 119','Что происходит при звонке на 119','撥打119之後會發生咩事'),
  costTitle:  L('Cost Information','費用について','费用信息','費用資訊','비용 안내','Información de Costos','Informations sur les coûts','Informazioni sui costi','Impormasyon sa Gastos','Informasi Biaya','Kosteninformationen','Informações de Custo','Информация о стоимости','費用資料'),
  notEmergency: L('Not an emergency? Try #7119 instead','緊急ではない場合は #7119 へ','非紧急情况？请拨打 #7119','非緊急情況？請撥打 #7119','응급이 아닌 경우 #7119로 전화하세요','¿No es urgente? Pruebe el #7119','Pas urgent ? Essayez le #7119','Non urgente? Prova il #7119','Hindi emergency? Tumawag sa #7119','Tidak darurat? Coba #7119','Kein Notfall? Versuchen Sie #7119','Não é urgente? Tente o #7119','Не экстренная? Позвоните #7119','唔係緊急情況？可以改打 #7119'),
}

export const HOTLINE = {
  title:      L('#7119 & #8000','#7119 & #8000','#7119 & #8000','#7119 & #8000','#7119 & #8000','#7119 y #8000','#7119 et #8000','#7119 e #8000','#7119 at #8000','#7119 & #8000','#7119 & #8000','#7119 e #8000','#7119 и #8000','#7119 & #8000'),
  subtitle:   L('Free consultation hotlines before going to a hospital.','病院に行く前の無料相談ダイヤル。','去医院前的免费咨询热线。','去醫院前的免費諮詢熱線。','병원 가기 전 무료 상담 전화。','Líneas de consulta gratuitas antes de ir al hospital.','Lignes de consultation gratuites avant d\'aller à l\'hôpital.','Linee di consulenza gratuite prima di andare in ospedale.','Libreng hotline bago pumunta sa ospital.','Hotline konsultasi gratis sebelum ke rumah sakit.','Kostenlose Beratungshotlines vor dem Krankenhausbesuch.','Linhas de consulta gratuitas antes de ir ao hospital.','Бесплатные консультационные линии перед визитом в больницу.','去醫院之前嘅免費諮詢熱線。'),
  otherNums:  L('Other Useful Numbers','その他の便利な番号','其他有用号码','其他有用號碼','기타 유용한 번호','Otros Números Útiles','Autres Numéros Utiles','Altri Numeri Utili','Iba Pang Mga Numero','Nomor Berguna Lainnya','Weitere nützliche Nummern','Outros Números Úteis','Другие полезные номера','其他有用號碼'),
}

export const NIGHTCARE = {
  title:      L('Night & Holiday Care','夜間・休日診療','夜间及节假日医疗','夜間及假日醫療','야간 및 휴일 진료','Atención Nocturna y Festiva','Soins de Nuit et Jours Fériés','Cure Notturne e Festive','Gabi at Holiday na Pangangalaga','Perawatan Malam & Hari Libur','Nacht- und Feiertagsversorgung','Atendimento Noturno e Feriados','Ночная и праздничная помощь','夜間及假日醫療'),
  subtitle:   L('How to access medical care outside regular hours in Japan.','日本での時間外医療へのアクセス方法。','在日本如何获得非常规时间的医疗。','在日本如何獲得非常規時間的醫療。','일본에서 정규 시간 외 의료 이용 방법。','Cómo acceder a atención médica fuera del horario habitual.','Comment accéder aux soins en dehors des heures normales.','Come accedere alle cure mediche fuori orario.','Paano makakuha ng medikal na pag-aalaga sa labas ng oras.','Cara mengakses layanan medis di luar jam biasa.','Medizinische Versorgung außerhalb der regulären Zeiten.','Como acessar cuidados médicos fora do horário normal.','Как получить медицинскую помощь во внеурочное время.','喺日本非正常時間點樣獲得醫療服務。'),
  typesTitle: L('Types of After-Hours Clinics','時間外クリニックの種類','时间外诊所类型','時間外診所類型','시간 외 클리닉 유형','Tipos de Clínicas Fuera de Horario','Types de Cliniques Hors Horaires','Tipi di Cliniche Fuori Orario','Mga Uri ng After-Hours Clinics','Jenis Klinik Luar Jam','Arten von Notfall-Kliniken','Tipos de Clínicas Fora do Horário','Виды внеплановых клиник','非正常時間診所類型'),
  howToFind:  L('How to Find a Clinic Near You','近くのクリニックを見つける方法','如何找到附近的诊所','如何找到附近的診所','근처 클리닉 찾는 방법','Cómo encontrar una clínica cercana','Comment trouver une clinique proche','Come trovare una clinica vicina','Paano Mahanap ang Klinika sa Malapit','Cara Menemukan Klinik Terdekat','So finden Sie eine Klinik in der Nähe','Como encontrar uma clínica perto','Как найти ближайшую клинику','點樣搵附近嘅診所'),
  whatToBring:L('What to Bring','持参するもの','需要携带的物品','需要攜帶的物品','가져갈 것들','Qué Llevar','Ce qu\'il faut apporter','Cosa Portare','Mga Dala','Yang Perlu Dibawa','Was mitbringen','O Que Levar','Что взять с собой','需要帶咩嘢'),
}

export const CHECKLIST = {
  title:      L('Preparation Checklist','準備チェックリスト','准备清单','準備清單','준비 체크리스트','Lista de Preparación','Liste de Préparation','Lista di Preparazione','Listahan ng Paghahanda','Daftar Persiapan','Vorbereitungscheckliste','Lista de Preparação','Контрольный список','準備清單'),
  subtitle:   L('Everything you should bring to a hospital or clinic visit in Japan.','日本の病院・クリニック受診時に持参するもの。','在日本就医时应携带的所有物品。','在日本就醫時應攜帶的所有物品。','일본 병원/클리닉 방문 시 가져갈 것들.','Todo lo que debes llevar al médico en Japón.','Tout ce que vous devez apporter à la clinique au Japon.','Tutto ciò che dovresti portare in ospedale in Giappone.','Lahat ng dapat dalhin sa ospital sa Japan.','Semua yang perlu dibawa ke rumah sakit di Jepang.','Alles, was Sie ins Krankenhaus mitnehmen sollten.','Tudo que você deve levar ao médico no Japão.','Всё, что нужно взять в больницу в Японии.','喺日本睇醫生時應該帶備嘅物品。'),
  packed:     L('Items packed','持参済みアイテム','已准备物品','已準備物品','준비된 항목','Artículos listos','Articles préparés','Oggetti preparati','Mga item na handa','Item yang sudah siap','Gepäckte Artikel','Itens preparados','Собранные вещи','已準備物品'),
  reset:      L('Reset','リセット','重置','重置','초기화','Restablecer','Réinitialiser','Reimposta','I-reset','Setel ulang','Zurücksetzen','Redefinir','Сбросить','重置'),
  tipBody:    L('Screenshot this checklist or save it offline before your visit in case you don\'t have internet access at the hospital.','受診前にこのリストをスクリーンショットするか、オフラインで保存してください。病院でインターネットが使えない場合に備えて。','就医前截图保存此清单，以备医院无网络时使用。','就醫前截圖保存此清單，以備醫院無網路時使用。','병원에 인터넷이 없을 경우를 대비해 방문 전에 스크린샷을 찍거나 오프라인으로 저장하세요。','Captura esta lista o guárdala sin conexión antes de tu visita.','Faites une capture d\'écran ou sauvegardez cette liste hors ligne.','Fai uno screenshot di questa lista prima della visita.','I-screenshot ang listahang ito bago ang iyong pagbisita.','Screenshot daftar ini sebelum kunjungan Anda.','Machen Sie vor Ihrem Besuch einen Screenshot dieser Liste.','Tire um print desta lista antes de sua visita.','Сделайте скриншот этого списка перед визитом.','睇醫生之前截圖儲存呢張清單，以備醫院無網絡時使用。'),
  sections: {
    docs:    L('Essential Documents','必要書類','必要文件','必要文件','필수 서류','Documentos Esenciales','Documents Essentiels','Documenti Essenziali','Mahahalagang Dokumento','Dokumen Penting','Wichtige Dokumente','Documentos Essenciais','Необходимые документы','必要文件'),
    payment: L('Payment','支払い方法','付款','付款','결제','Pago','Paiement','Pagamento','Bayad','Pembayaran','Zahlung','Pagamento','Оплата','付款方式'),
    medical: L('Medical Information','医療情報','医疗信息','醫療資訊','의료 정보','Información Médica','Informations Médicales','Informazioni Mediche','Medikal na Impormasyon','Informasi Medis','Medizinische Informationen','Informações Médicas','Медицинская информация','醫療資料'),
    comms:   L('Communication','コミュニケーション','沟通工具','溝通工具','의사소통','Comunicación','Communication','Comunicazione','Komunikasyon','Komunikasi','Kommunikation','Comunicação','Общение','溝通方式'),
  },
}

export const EMERGENCY = {
  title:     L('Emergency Numbers','緊急連絡先','紧急电话号码','緊急電話號碼','긴급 전화번호','Números de Emergencia','Numéros d\'Urgence','Numeri di Emergenza','Mga Numero ng Emergency','Nomor Darurat','Notfallnummern','Números de Emergência','Экстренные номера','緊急電話號碼'),
  subtitle:  L('Key emergency numbers to know in Japan.','日本で知っておくべき緊急番号。','在日本需要知道的紧急电话。','在日本需要知道的緊急電話。','일본에서 알아야 할 긴급 번호.','Números de emergencia clave en Japón.','Numéros d\'urgence essentiels au Japon.','Numeri di emergenza essenziali in Giappone.','Mga mahalagang numero ng emergency sa Japan.','Nomor darurat penting di Jepang.','Wichtige Notrufnummern in Japan.','Números de emergência essenciais no Japão.','Основные экстренные номера в Японии.','喺日本需要知道嘅緊急電話。'),
  whenTitle: L('When to Call 119 vs. Wait','119番 vs. 待機の判断','何时拨打119 vs. 等待','何時撥打119 vs. 等待','119 vs. 대기 기준','Cuándo llamar al 119 vs. Esperar','Quand appeler le 119 vs. Attendre','Quando chiamare il 119 vs. Aspettare','Kailan Tatawag ng 119 vs. Hintayin','Kapan Menghubungi 119 vs. Menunggu','Wann 119 anrufen vs. Warten','Quando ligar 119 vs. Esperar','Когда звонить 119 или ждать','幾時打119 vs. 等候'),
  tipsTitle: L('Tips for Calling as a Foreigner','外国人として119番に電話する際のコツ','作为外国人拨打119的建议','作為外國人撥打119的建議','외국인으로서 119에 전화할 때 팁','Consejos para llamar como extranjero','Conseils pour appeler en tant qu\'étranger','Consigli per chiamare come straniero','Mga Tip sa Pagtawag bilang Dayuhan','Tips Menelepon sebagai Orang Asing','Tipps für Ausländer beim Anruf','Dicas para ligar como estrangeiro','Советы для иностранцев при звонке','外國人打119嘅貼士'),
}

export const SEARCH = {
  title:    L('Search','検索','搜索','搜索','검색','Buscar','Recherche','Ricerca','Paghahanap','Cari','Suche','Buscar','Поиск','搜尋'),
  subtitle: L('Find information about healthcare in Japan.','日本の医療情報を検索。','查找日本医疗信息。','查找日本醫療資訊。','일본 의료 정보 검색.','Busca información sobre salud en Japón.','Trouvez des informations sur la santé au Japon.','Trova informazioni sanitarie in Giappone.','Maghanap ng impormasyon sa kalusugan sa Japan.','Temukan informasi kesehatan di Jepang.','Gesundheitsinformationen in Japan finden.','Encontre informações de saúde no Japão.','Поиск информации о здравоохранении в Японии.','搵尋日本嘅醫療資訊。'),
  placeholder: L('Search symptoms or keywords...','症状やキーワードを入力...','搜索症状或关键词...','搜索症狀或關鍵詞...','증상이나 키워드 검색...','Busca síntomas o palabras clave...','Recherchez des symptômes ou mots-clés...','Cerca sintomi o parole chiave...','Maghanap ng sintomas o keyword...','Cari gejala atau kata kunci...','Symptome oder Stichwörter suchen...','Pesquise sintomas ou palavras-chave...','Поиск симптомов или ключевых слов...','搜尋症狀或關鍵詞...'),
  noResults:L('No results found.','結果が見つかりませんでした。','未找到结果。','未找到結果。','결과가 없습니다.','Sin resultados.','Aucun résultat.','Nessun risultato.','Walang nahanap.','Tidak ada hasil.','Keine Ergebnisse.','Sem resultados.','Результатов не найдено.','冇搵到結果。'),
  cats: {
    all:       L('All','すべて','全部','全部','전체','Todo','Tout','Tutto','Lahat','Semua','Alle','Todos','Все','全部'),
    symptoms:  L('Symptoms','症状','症状','症狀','증상','Síntomas','Symptômes','Sintomi','Sintomas','Gejala','Symptome','Sintomas','Симптомы','症狀'),
    hospitals: L('Hospitals','病院','医院','醫院','병원','Hospitales','Hôpitaux','Ospedali','Ospital','Rumah Sakit','Krankenhäuser','Hospitais','Больницы','醫院'),
    insurance: L('Insurance','保険','保险','保險','보험','Seguro','Assurance','Assicurazione','Seguro','Asuransi','Versicherung','Seguro','Страхование','保險'),
    medicine:  L('Medicine','薬','药品','藥品','약','Medicamentos','Médicaments','Medicinali','Gamot','Obat','Medikamente','Medicamentos','Лекарства','藥物'),
    emergency: L('Emergency','緊急','紧急','緊急','긴급','Emergencia','Urgence','Emergenza','Emergency','Darurat','Notfall','Emergência','Экстренная помощь','緊急'),
  },
}

export const SAVED_PAGE = {
  title:     L('Saved','保存済み','已收藏','已收藏','저장됨','Guardados','Enregistrés','Salvati','Na-save','Tersimpan','Gespeichert','Salvos','Сохранённое','已儲存'),
  subtitle:  L('Your bookmarked guides and articles.','ブックマークしたガイドと記事。','您收藏的指南和文章。','您收藏的指南和文章。','북마크된 가이드 및 기사.','Guías y artículos guardados.','Vos guides et articles enregistrés.','Le tue guide e articoli salvati.','Mga naka-save na gabay at artikulo.','Panduan dan artikel yang disimpan.','Gespeicherte Anleitungen und Artikel.','Guias e artigos salvos.','Сохранённые руководства и статьи.','你書籤咗嘅指南同文章。'),
  empty:     L('No saved items yet','まだ保存されたアイテムがありません','还没有收藏的内容','還沒有收藏的內容','아직 저장된 항목이 없습니다','Aún no hay artículos guardados','Aucun article enregistré pour l\'instant','Nessun articolo salvato ancora','Wala pang naka-save na item','Belum ada item yang disimpan','Noch keine gespeicherten Artikel','Nenhum item salvo ainda','Нет сохранённых элементов','未有儲存任何項目'),
  emptyDesc: L('Tap the bookmark icon on any page to save it here.','各ページのブックマークアイコンをタップして保存。','点击任意页面的书签图标以保存至此处。','點擊任意頁面的書籤圖示以保存至此處。','페이지의 북마크 아이콘을 눌러 저장하세요.','Toca el ícono de marcador en cualquier página.','Appuyez sur l\'icône signet sur n\'importe quelle page.','Tocca l\'icona segnalibro su qualsiasi pagina.','I-tap ang bookmark icon sa anumang pahina.','Ketuk ikon bookmark di halaman mana saja.','Tippen Sie auf das Lesezeichen-Symbol.','Toque o ícone de marcador em qualquer página.','Нажмите на значок закладки на любой странице.','喺任何頁面點按書籤圖示即可儲存至此處。'),
  browse:    L('Browse Articles','記事を見る','浏览文章','瀏覽文章','기사 보기','Ver Artículos','Parcourir les articles','Sfoglia gli articoli','Mag-browse ng mga Artikulo','Jelajahi Artikel','Artikel durchsuchen','Explorar Artigos','Просмотр статей','瀏覽文章'),
  recommended:L('Recommended for You','おすすめ','为您推荐','為您推薦','추천','Recomendado','Recommandé','Consigliato','Inirerekomenda','Direkomendasikan','Empfohlen','Recomendado','Рекомендовано','為你推薦'),
}

export const HEALTHCHECK = {
  title:    L('Check Current Health Status','今の健康状態を確認する','检查当前健康状况','檢查當前健康狀況','현재 건강 상태 확인','Verificar Estado de Salud','Vérifier l\'état de santé','Controlla lo Stato di Salute','Suriin ang Kasalukuyang Kalusugan','Periksa Status Kesehatan','Gesundheitsstatus prüfen','Verificar Estado de Saúde','Проверить состояние здоровья','檢查當前健康狀況'),
  subtitle: L('Answer a few questions to find the right action for your situation.','質問に答えて、適切な対応方法を見つけましょう。','回答几个问题，找到适合您情况的正确措施。','回答幾個問題，找到適合您情況的正確措施。','몇 가지 질문에 답해 적절한 대처법을 찾으세요.','Responde algunas preguntas para encontrar la acción correcta.','Répondez à quelques questions pour trouver la bonne action.','Rispondi a qualche domanda per trovare l\'azione giusta.','Sagutin ang ilang tanong para mahanap ang tamang aksyon.','Jawab beberapa pertanyaan untuk menemukan tindakan yang tepat.','Beantworten Sie einige Fragen für die richtige Maßnahme.','Responda algumas perguntas para encontrar a ação certa.','Ответьте на несколько вопросов для правильных действий.','回答幾個問題，搵到適合你情況嘅正確措施。'),
  startOver:L('Start Over','もう一度試す','重新开始','重新開始','다시 시작','Empezar de Nuevo','Recommencer','Ricomincia','Magsimula Muli','Mulai Lagi','Neu starten','Recomeçar','Начать заново','重新開始'),
  related:  L('Related Guides','関連ガイド','相关指南','相關指南','관련 가이드','Guías Relacionadas','Guides Connexes','Guide Correlate','Mga Kaugnay na Gabay','Panduan Terkait','Verwandte Anleitungen','Guias Relacionados','Связанные руководства','相關指南'),
}

export const ARTICLES = {
  category: L('Insights','インサイト','见解','見解','인사이트','Perspectivas','Perspectives','Approfondimenti','Mga Pananaw','Wawasan','Einblicke','Perspectivas','Аналитика','見解'),
  surprises: {
    title:   L('Surprises in Japanese Hospitals','日本の病院で驚くこと','在日本医院的意外发现','在日本醫院的意外發現','일본 병원에서 놀라운 점','Sorpresas en Hospitales Japoneses','Surprises dans les Hôpitaux Japonais','Sorprese negli Ospedali Giapponesi','Mga Sorpresa sa mga Ospital sa Japan','Kejutan di Rumah Sakit Jepang','Überraschungen in japanischen Krankenhäusern','Surpresas nos Hospitais Japoneses','Сюрпризы в японских больницах','喺日本醫院嘅意外發現'),
    sub:     L('What to expect if it\'s your first visit','初めて受診する方へ','初次就医的注意事项','初次就醫的注意事項','처음 방문하는 분께','Qué esperar en tu primera visita','À quoi s\'attendre lors de votre première visite','Cosa aspettarsi alla prima visita','Ano ang asahan sa unang pagbisita','Apa yang diharapkan saat pertama kali','Was Sie beim ersten Besuch erwartet','O que esperar na primeira visita','Чего ожидать при первом визите','初次睇醫生嘅注意事項'),
    bottom:  L('Bottom line:','まとめ:','总结：','總結：','결론:','Conclusión:','En résumé:','In sintesi:','Buod:','Kesimpulan:','Fazit:','Conclusão:','Итог:','總結：'),
  },
  waitTimes: {
    title:   L('Why Wait Times Are Long in Japan','日本の待ち時間が長い理由','为什么日本等待时间很长','為什麼日本等待時間很長','일본의 대기 시간이 긴 이유','Por Qué Los Tiempos de Espera Son Largos','Pourquoi les Temps d\'Attente Sont Longs','Perché i Tempi di Attesa Sono Lunghi','Bakit Mahaba ang Oras ng Paghihintay','Mengapa Waktu Tunggu Lama di Jepang','Warum Wartezeiten in Japan Lang Sind','Por Que os Tempos de Espera São Longos','Почему в Японии долго ждать','點解日本等待時間咁長'),
    sub:     L('Understanding the system helps you plan better','仕組みを理解して上手に計画を','了解制度有助于更好地规划','了解制度有助於更好地規劃','시스템 이해로 더 나은 계획 세우기','Entender el sistema ayuda a planificar','Comprendre le système aide à mieux planifier','Capire il sistema aiuta a pianificare meglio','Ang pag-unawa sa sistema ay nakakatulong','Memahami sistem membantu perencanaan','Das System verstehen hilft beim Planen','Entender o sistema ajuda a planejar','Понимание системы поможет планировать','了解制度有助於更好地計劃'),
  },
  lateNight: {
    title:   L('Getting Medicine Late at Night','夜間に薬を入手する方法','深夜获取药品的方法','深夜獲取藥品的方法','늦은 밤 약 구하는 방법','Conseguir Medicamentos de Madrugada','Obtenir des Médicaments la Nuit','Procurarsi Medicine di Notte','Pagkuha ng Gamot sa Gabi','Mendapatkan Obat di Malam Hari','Medikamente Spät Nachts Bekommen','Conseguir Remédios à Noite','Как достать лекарства поздно ночью','深夜搵藥嘅方法'),
    sub:     L('Your options when pharmacies are closed','薬局が閉まっている時の選択肢','药店关闭时的选择','藥局關閉時的選擇','약국이 닫혔을 때 선택지','Sus opciones cuando las farmacias están cerradas','Vos options quand les pharmacies sont fermées','Le tue opzioni quando le farmacie sono chiuse','Mga pagpipilian kapag sarado ang parmasya','Pilihan saat apotek tutup','Ihre Optionen wenn Apotheken geschlossen sind','Suas opções quando as farmácias estão fechadas','Варианты, когда аптеки закрыты','藥房關閉時嘅選擇'),
  },
}

export const HOME = {
  tag:      L('Medical Guide Portal','医療ガイドポータル','医疗指南门户','醫療指南門戶','의료 가이드 포털','Portal de Guía Médica','Portail Guide Médical','Portale Guida Medica','Portal ng Medikal na Gabay','Portal Panduan Medis','Medizinischer Leitfaden','Portal Guia Médico','Медицинский портал','醫療指南門戶'),
  h1:       L('Japanese Healthcare,','日本の医療を、','日本医疗，','日本醫療，','일본 의료,','Salud Japonesa,','Santé Japonaise,','Sanità Giapponese,','Pangangalagang Pangkalusugan sa Japan,','Kesehatan Jepang,','Japanische Gesundheit,','Saúde Japonesa,','Здравоохранение Японии,','日本醫療，'),
  h2:       L('Within Your Reach.','あなたの手の届く場所に。','触手可及。','觸手可及。','당신의 손 닿는 곳에.','A tu alcance.','À votre portée.','Alla tua portata.','Sa Iyong Kamay.','Dalam Jangkauan Anda.','Zum Greifen nah.','Ao seu alcance.','В пределах досягаемости.','就喺你身邊。'),
  unsure:   L('Not sure what to do?','どうすればいいかわからない？','不知道该怎么办？','不知道該怎麼辦？','어떻게 해야 할지 모르겠나요?','¿No sabes qué hacer?','Vous ne savez pas quoi faire?','Non sai cosa fare?','Hindi alam ang gagawin?','Tidak tahu harus berbuat apa?','Nicht sicher was zu tun?','Não sabe o que fazer?','Не знаете что делать?','唔知點算好？'),
  hub:      L('Assessment Hub','症状チェック','症状评估','症狀評估','증상 평가','Evaluación','Évaluation','Valutazione','Pagsusuri','Penilaian','Bewertung','Avaliação','Оценка','症狀評估'),
  hubDesc:  L("We'll guide you to the right medical care based on your symptoms and concerns.",'症状や状況に応じて、適切な医療機関へご案内します。','我们将根据您的症状和需求，引导您获得正确的医疗服务。','我們將根據您的症狀和需求，引導您獲得正確的醫療服務。','증상과 상황에 맞는 의료 서비스로 안내해 드립니다.','Le guiaremos al cuidado médico correcto según sus síntomas.','Nous vous guiderons vers les soins médicaux appropriés.','Vi guideremo verso le cure mediche giuste per voi.','Gagabayan kayo sa tamang medikal na pag-aalaga.','Kami akan memandu Anda ke layanan medis yang tepat.','Wir leiten Sie zur richtigen medizinischen Versorgung.','Vamos guiá-lo ao cuidado médico certo para você.','Мы направим вас к нужной медицинской помощи.','我哋會根據你嘅症狀同需要，引導你獲得正確嘅醫療服務。'),
  sym0:     L('Sudden Fever','急な発熱','突发发烧','突發發燒','갑작스러운 발열','Fiebre Repentina','Fièvre Soudaine','Febbre Improvvisa','Biglang Lagnat','Demam Mendadak','Plötzliches Fieber','Febre Repentina','Внезапная температура','突發發燒'),
  sym1:     L('Injury / Burn','ケガ・やけど','受伤/烧伤','受傷/燒傷','부상/화상','Lesión / Quemadura','Blessure / Brûlure','Lesione / Ustione','Sugat / Paso','Cedera / Luka Bakar','Verletzung / Verbrennung','Lesão / Queimadura','Травма / Ожог','受傷／燒傷'),
  sym2:     L('Late Night Illness','夜間の体調不良','深夜生病','深夜生病','야간 질병','Enfermedad Nocturna','Maladie Nocturne','Malattia Notturna','Sakit sa Gabi','Sakit Malam Hari','Nächtliche Erkrankung','Doença Noturna','Ночное недомогание','深夜不適'),
  sym3:     L('Unsure Where to Go','どこへ行けばいいか','不知道去哪里','不知道去哪裡','어디 가야 할지 모름','No sé adónde ir','Je ne sais pas où aller','Non so dove andare','Hindi alam kung saan pupunta','Tidak tahu harus ke mana','Nicht sicher wohin','Não sei para onde ir','Не знаю куда идти','唔知去邊好'),
  checkBtn: L('Check Current Health Status','今の健康状態を確認する','检查当前健康状况','檢查當前健康狀況','현재 건강 상태 확인','Verificar Estado de Salud','Vérifier l\'état de santé','Controlla lo Stato di Salute','Suriin ang Kalusugan','Periksa Status Kesehatan','Gesundheitsstatus prüfen','Verificar Estado de Saúde','Проверить здоровье','檢查當前健康狀況'),
  search:   L('Enter symptoms or keywords','症状やキーワードを入力','输入症状或关键词','輸入症狀或關鍵詞','증상이나 키워드 입력','Ingresa síntomas o palabras','Entrez des symptômes','Inserisci sintomi o parole','Ilagay ang sintomas','Masukkan gejala','Symptome eingeben','Insira sintomas','Введите симптомы','輸入症狀或關鍵詞'),
  popular:  L('Popular:','よく検索:','热门搜索:','熱門搜索:','인기:','Popular:','Populaire:','Popolare:','Popular:','Populer:','Beliebt:','Popular:','Популярно:','熱門搜尋：'),
  actNow:   L('Act Now','今すぐ行動','立即行动','立即行動','지금 바로','Actúa Ahora','Agissez Maintenant','Agisci Ora','Kumilos Ngayon','Bertindak Sekarang','Jetzt handeln','Aja Agora','Действуй сейчас','立即行動'),
  actSub:   L('Immediate Actions','緊急対応','立即措施','立即措施','즉각 조치','Acciones Inmediatas','Actions Immédiates','Azioni Immediate','Agarang Aksyon','Tindakan Segera','Sofortmaßnahmen','Ações Imediatas','Немедленные действия','即時措施'),
  system:   L('Understand the System','仕組みを理解する','了解制度','了解制度','제도 이해','Entender el Sistema','Comprendre le Système','Capire il Sistema','Unawain ang Sistema','Pahami Sistem','Das System verstehen','Entender o Sistema','Понять систему','了解醫療制度'),
  systemSub:L('How it works','日本の医療制度','如何运作','如何運作','작동 원리','Cómo funciona','Comment ça marche','Come funziona','Paano gumagana','Cara kerjanya','Wie es funktioniert','Como funciona','Как это работает','係點運作嘅'),
  insights: L('Insights & Guides','ガイド & 解説','见解与指南','見解與指南','인사이트 & 가이드','Perspectivas y Guías','Perspectives et Guides','Approfondimenti e Guide','Mga Pananaw at Gabay','Wawasan & Panduan','Einblicke & Anleitungen','Perspectivas e Guias','Аналитика и руководства','見解與指南'),
  insSub:   L('Mini-Columns','コラム','迷你专栏','迷你專欄','미니 칼럼','Mini-Columnas','Mini-Chroniques','Mini-Colonne','Mga Mini-Kolumna','Mini-Kolom','Mini-Kolumnen','Mini-Colunas','Мини-колонки','迷你專欄'),
  whoAreYou:L('Who are you visiting as?','あなたの状況は？','您的身份是？','您的身份是？','방문 유형은?','¿Cómo nos visitas?','Qui êtes-vous?','Chi sei?','Sino ka?','Siapa Anda?','Wer sind Sie?','Quem é você?','Кто вы?','你係以咩身份嚟？'),
  whoSub:   L('We\'ll show information relevant to your situation.','状況に合った情報をお届けします。','我们将显示与您情况相关的信息。','我們將顯示與您情況相關的信息。','상황에 맞는 정보를 보여드립니다.','Mostraremos información relevante para su situación.','Nous afficherons des informations pertinentes.','Mostreremo informazioni pertinenti.','Magpapakita ng kaugnay na impormasyon.','Kami akan menampilkan informasi yang relevan.','Wir zeigen relevante Informationen.','Mostraremos informações relevantes.','Мы покажем актуальную информацию.','我哋會顯示適合你情況嘅資訊。'),
  change:   L('Change','変更','更改','更改','변경','Cambiar','Modifier','Cambia','Baguhin','Ubah','Ändern','Alterar','Изменить','更改'),
}

export const RESIDENCY = {
  tourist:  L('Short-term visitor','短期旅行者','短期游客','短期遊客','단기 여행자','Visitante de corta estadía','Visiteur de courte durée','Visitatore a breve termine','Panandaliang bisita','Wisatawan jangka pendek','Kurzzeitbesucher','Visitante de curta duração','Краткосрочный посетитель','短期旅遊者'),
  newcomer: L('New arrival (< 6 months)','来日6ヶ月未満','新来者（< 6个月）','新來者（< 6個月）','신규 입국자 (6개월 미만)','Recién llegado (< 6 meses)','Nouvel arrivant (< 6 mois)','Nuovo arrivato (< 6 mesi)','Bagong dating (< 6 buwan)','Pendatang baru (< 6 bulan)','Neuankömmling (< 6 Monate)','Recém-chegado (< 6 meses)','Недавно прибывший (< 6 мес.)','新嚟者（< 6個月）'),
  resident: L('Long-term / Permanent resident','長期在留・永住者','长期/永久居民','長期/永久居民','장기 거주자/영주권자','Residente de larga duración','Résident long terme','Residente a lungo termine','Matagalang naninirahan','Penduduk jangka panjang','Langzeitbewohner','Residente de longa duração','Долгосрочный/постоянный житель','長期／永久居民'),
  touristDesc: L('Passport only · No NHI · Travel insurance recommended','パスポートのみ・NHI非対象・旅行保険推奨','仅护照 · 无NHI · 建议购买旅游保险','僅護照 · 無NHI · 建議購買旅遊保險','여권만 · NHI 없음 · 여행보험 권장','Solo pasaporte · Sin NHI · Seguro recomendado','Passeport seulement · Pas de NHI · Assurance voyage recommandée','Solo passaporto · Niente NHI · Assicurazione viaggio consigliata','Pasaporte lang · Walang NHI · Inirerekomendang travel insurance','Paspor saja · Tanpa NHI · Asuransi perjalanan disarankan','Nur Reisepass · Kein NHI · Reiseversicherung empfohlen','Apenas passaporte · Sem NHI · Seguro viagem recomendado','Только паспорт · Без NHI · Страховка рекомендована','僅護照 · 非NHI對象 · 建議購買旅遊保險'),
  newcomerDesc:L('Residence card · Enroll in NHI within 14 days · 30% co-pay','在留カード・14日以内にNHI加入・3割負担','在留卡 · 14天内加入NHI · 自付30%','在留卡 · 14天內加入NHI · 自付30%','재류카드 · 14일 내 NHI 가입 · 30% 본인부담','Tarjeta de residencia · Inscríbete en NHI en 14 días · 30% copago','Carte de résidence · Inscrivez-vous au NHI sous 14 jours · 30% ticket','Carta di residenza · Iscriviti al NHI entro 14 giorni · 30% contributo','Residence card · Mag-enroll sa NHI sa loob ng 14 araw · 30% babayaran','Kartu residensi · Daftar NHI dalam 14 hari · Bayar 30%','Aufenthaltstitel · NHI innerhalb 14 Tagen · 30% Eigenanteil','Cartão de residência · Inscreva-se no NHI em 14 dias · 30% copagamento','Карта резидента · Запись в NHI в течение 14 дней · 30% доплата','在留卡 · 14日內加入NHI (國民健康保險) · 自付30%'),
  residentDesc:L('Insurance card + Residence card · NHI / Work insurance · 30% co-pay','保険証＋在留カード・NHI/社保加入済・3割負担','保险卡+在留卡 · 已参加NHI/社保 · 自付30%','保險卡+在留卡 · 已參加NHI/社保 · 自付30%','보험증+재류카드 · NHI/직장보험 가입 · 30% 본인부담','Tarjeta seguro + residencia · NHI/seguro laboral · 30% copago','Carte assurance + résidence · NHI/assurance travail · 30% ticket','Tessera sanitaria + residenza · NHI/assicurazione lavoro · 30%','Insurance card + residence card · NHI/work insurance · 30%','Kartu asuransi + residensi · NHI/asuransi kerja · 30%','Versicherungskarte + Aufenthaltstitel · NHI/Arbeit · 30%','Cartão seguro + residência · NHI/plano trabalho · 30%','Страховка + карта резидента · NHI/рабочая страховка · 30%','保險卡 (Health Insurance Card) + 在留卡 · 已加入NHI/社保 · 自付30%'),
}
